/**
 * gcode/3mf metadata parser tests. See docs/KHAYT-3.0-PRINTFILES-SPEC.md.
 * Covers the slicers Khayt targets and the footer-summary case the previous
 * head-only reader missed.
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { parseGcodeText, parsePrintTimeMins, parseFilamentGrams, detectSlicer } = require('../lib/gcode-parse.js');

test('PrusaSlicer footer summary (the case the old head-only read missed)', () => {
  // PrusaSlicer writes this block at the END of the file.
  const footer = [
    '; prusaslicer_config = begin',
    '; estimated printing time (normal mode) = 2h 5m 30s',
    '; filament used [g] = 14.83',
    '; prusaslicer_config = end',
  ].join('\n');
  const r = parseGcodeText(footer);
  assert.equal(r.printTimeMins, 126, '2h5m30s -> 126 min (seconds rounded)');
  assert.equal(r.filamentGrams, 14.83);
});

test('PrusaSlicer with days + multi-extruder filament sums', () => {
  const txt = [
    '; estimated printing time (normal mode) = 1d 2h 0m 0s',
    '; filament used [g] = 10.5, 4.5',
  ].join('\n');
  assert.equal(parsePrintTimeMins(txt), 1560, '1d2h = 1560 min');
  assert.equal(parseFilamentGrams(txt), 15, 'multi-extruder grams summed');
});

test('"total filament used [g]" wins over per-extruder list', () => {
  const txt = [
    '; filament used [g] = 10.5, 4.5',
    '; total filament used [g] = 15.0',
  ].join('\n');
  assert.equal(parseFilamentGrams(txt), 15.0);
});

test('Cura header: ;TIME and FILAMENT_WEIGHT', () => {
  const head = [
    ';FLAVOR:Marlin',
    ';TIME:7530',
    ';Filament used: 1.85m',
    ';FILAMENT_WEIGHT = 22.4',
  ].join('\n');
  const r = parseGcodeText(head);
  assert.equal(r.printTimeMins, 126, '7530s -> 126 min');
  assert.equal(r.filamentGrams, 22.4);
});

test('Bambu Studio: colon-separated time + total filament weight', () => {
  const txt = [
    '; total estimated time: 1h 4m 5s',
    '; total filament weight [g] : 31.2',
    '; BambuStudio 1.8',
  ].join('\n');
  const r = parseGcodeText(txt);
  assert.equal(r.printTimeMins, 64, '1h4m5s -> 64 min');
  assert.equal(r.filamentGrams, 31.2);
  assert.equal(r.slicer, 'BambuStudio');
});

test('OrcaSlicer colon separators', () => {
  const txt = [
    '; OrcaSlicer 2.0',
    '; estimated printing time (normal mode) = 0h 45m 0s',
    '; filament used [g] : 8.0',
  ].join('\n');
  const r = parseGcodeText(txt);
  assert.equal(r.printTimeMins, 45);
  assert.equal(r.filamentGrams, 8.0);
  assert.equal(r.slicer, 'OrcaSlicer');
});

test('head+tail concatenation parses a summary located only in the tail', () => {
  const head = ';FLAVOR:Marlin\nG28\nG1 X0 Y0\n';        // movement, no summary
  const tail = '; estimated printing time (normal mode) = 0h 30m 0s\n; filament used [g] = 5.0\n';
  const r = parseGcodeText(head + '\n' + tail);             // mimics the head+tail read
  assert.equal(r.printTimeMins, 30);
  assert.equal(r.filamentGrams, 5.0);
});

test('no metadata → nulls (graceful, never throws)', () => {
  const r = parseGcodeText('G28\nG1 X10 Y10 E5\nG1 X20\n');
  assert.equal(r.printTimeMins, null);
  assert.equal(r.filamentGrams, null);
  assert.equal(r.slicer, null);
});

test('empty / nullish input is safe', () => {
  // The full shape, so a field added here has to be added deliberately.
  const empty = {
    printTimeMins: null, filamentGrams: null, filamentGramsDerived: false,
    filamentCm3: null, filamentType: null, filamentCost: null, slicer: null,
  };
  assert.deepEqual(parseGcodeText(''), empty);
  assert.deepEqual(parseGcodeText(null), empty);
  // Nothing to derive from, whatever density is offered.
  assert.deepEqual(parseGcodeText('', { densityGPerCm3: 1.24 }), empty);
});

test('parseFilamentCost extracts total filament cost', () => {
  const { parseFilamentCost } = require('../lib/gcode-parse.js');
  assert.equal(parseFilamentCost('; total filament cost = 1.87'), 1.87);
  assert.equal(parseFilamentCost('; filament cost = 0.50, 0.25'), 0.75, 'sums a per-extruder list');
  assert.equal(parseFilamentCost('; estimated printing time = 1h'), null);
  assert.equal(parseGcodeText('; total filament cost = 2.40\n; filament used [g] = 30').filamentCost, 2.40);
});

test('parseFilamentType extracts material (first extruder for multi-material)', () => {
  const { parseFilamentType } = require('../lib/gcode-parse.js');
  assert.equal(parseFilamentType('; filament_type = PLA'), 'PLA');
  assert.equal(parseFilamentType('; filament_type : PETG'), 'PETG');
  assert.equal(parseFilamentType('; filament_type = PLA;PETG'), 'PLA', 'first of a multi-material list');
  assert.equal(parseFilamentType('; estimated printing time = 1h'), null, 'no material → null');
  // surfaced on the full parse result
  assert.equal(parseGcodeText('; filament_type = ABS\n; filament used [g] = 5').filamentType, 'ABS');
});

test('detectSlicer recognizes the common slicers', () => {
  assert.equal(detectSlicer('; generated by PrusaSlicer 2.7'), 'PrusaSlicer');
  assert.equal(detectSlicer('; SuperSlicer 2.5'), 'SuperSlicer');
  assert.equal(detectSlicer('; Cura_SteamEngine 5.4'), 'Cura');
});

/* ---- A slice with no filament profile ------------------------------------
 * Verified against a real PrusaSlicer run on this machine: slicing a bare STL
 * with Khayt's own default args (`--export-gcode -o {output} {model}`) succeeds
 * and writes the footer below. The slicer measured the volume exactly and then
 * reported ZERO grams, because with no filament profile it has no density to
 * weigh it with. "Slice for exact quote" therefore filled in a time and left the
 * weight field empty — and weight is what material cost is priced from.
 *
 * The volume is the slicer's own measurement of real toolpaths, not a guess from
 * geometry, so grams is one multiplication away from the density the shop has
 * already configured.
 * ------------------------------------------------------------------------- */

// Verbatim from that run — do not tidy it; the 0.00 is the whole point.
const PROFILELESS = [
  '; generated by PrusaSlicer 2.9.2 on 2026-08-05',
  '; filament used [mm] = 1493.99',
  '; filament used [cm3] = 3.59',
  '; total filament used [g] = 0.00',
  '; total filament cost = 0.00',
  '; total filament used for wipe tower [g] = 0.00',
  '; estimated printing time (normal mode) = 13m 54s',
  '; filament_type = PLA',
].join('\n');

test('a slicer that could not weigh it reports no weight, not zero', () => {
  const m = parseGcodeText(PROFILELESS);
  assert.equal(m.filamentGrams, null, '0.00 g is an absence, never a measurement');
  assert.equal(m.filamentGramsDerived, false);
  assert.equal(m.filamentCm3, 3.59, 'but the volume it did measure is kept');
  assert.equal(m.printTimeMins, 14);
});

test('with the shop\'s density, that volume becomes a weight', () => {
  const m = parseGcodeText(PROFILELESS, { densityGPerCm3: 1.24 });
  assert.equal(m.filamentGrams, 4.45, '3.59 cm3 x 1.24');
  assert.equal(m.filamentGramsDerived, true, 'and says it was worked out, not weighed');
});

test('the shop\'s density is used, not a constant', () => {
  const petg = parseGcodeText(PROFILELESS, { densityGPerCm3: 1.27 });
  const abs = parseGcodeText(PROFILELESS, { densityGPerCm3: 1.04 });
  assert.ok(petg.filamentGrams > abs.filamentGrams, `${petg.filamentGrams} vs ${abs.filamentGrams}`);
  assert.equal(petg.filamentGrams, 4.56);
  assert.equal(abs.filamentGrams, 3.73);
});

test('a weight the slicer DID report is never overwritten by a derived one', () => {
  const weighed = PROFILELESS.replace('total filament used [g] = 0.00',
                                      'total filament used [g] = 41.83');
  const m = parseGcodeText(weighed, { densityGPerCm3: 99 });
  assert.equal(m.filamentGrams, 41.83, "the slicer's own figure wins");
  assert.equal(m.filamentGramsDerived, false);
});

test('no density means no derived weight — the old behaviour is unchanged', () => {
  const m = parseGcodeText(PROFILELESS);
  assert.equal(m.filamentGrams, null);
  for (const bad of [0, -1, null, undefined, NaN, 'x']) {
    assert.equal(parseGcodeText(PROFILELESS, { densityGPerCm3: bad }).filamentGrams, null, String(bad));
  }
});

test('mm3 is accepted as well as cm3', () => {
  const mm3 = PROFILELESS.replace('filament used [cm3] = 3.59', 'filament used [mm3] = 3590');
  assert.equal(parseGcodeText(mm3, { densityGPerCm3: 1.24 }).filamentGrams, 4.45);
});
