/**
 * gcode/3mf metadata parser tests. See docs/KHAYT-3.0-PRINTFILES-SPEC.md.
 * Covers the slicers Khayt targets and the footer-summary case the previous
 * head-only reader missed.
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { parseGcodeText, parsePrintTimeMins, parseFilamentGrams, detectSlicer } = require('../lib/gcode-parse.js');

test('PrusaSlicer footer summary (the case the old head-only read missed)', () => {
  // PrusaSlicer writes this block at the END of the file.
  const footer = [
    '; prusaslicer_config = begin',
    '; estimated printing time (normal mode) = 2h 5m 30s',
    '; filament used [g] = 14.83',
    '; prusaslicer_config = end',
  ].join('\n');
  const r = parseGcodeText(footer);
  assert.equal(r.printTimeMins, 126, '2h5m30s -> 126 min (seconds rounded)');
  assert.equal(r.filamentGrams, 14.83);
});

test('PrusaSlicer with days + multi-extruder filament sums', () => {
  const txt = [
    '; estimated printing time (normal mode) = 1d 2h 0m 0s',
    '; filament used [g] = 10.5, 4.5',
  ].join('\n');
  assert.equal(parsePrintTimeMins(txt), 1560, '1d2h = 1560 min');
  assert.equal(parseFilamentGrams(txt), 15, 'multi-extruder grams summed');
});

test('"total filament used [g]" wins over per-extruder list', () => {
  const txt = [
    '; filament used [g] = 10.5, 4.5',
    '; total filament used [g] = 15.0',
  ].join('\n');
  assert.equal(parseFilamentGrams(txt), 15.0);
});

test('Cura header: ;TIME and FILAMENT_WEIGHT', () => {
  const head = [
    ';FLAVOR:Marlin',
    ';TIME:7530',
    ';Filament used: 1.85m',
    ';FILAMENT_WEIGHT = 22.4',
  ].join('\n');
  const r = parseGcodeText(head);
  assert.equal(r.printTimeMins, 126, '7530s -> 126 min');
  assert.equal(r.filamentGrams, 22.4);
});

test('Bambu Studio: colon-separated time + total filament weight', () => {
  const txt = [
    '; total estimated time: 1h 4m 5s',
    '; total filament weight [g] : 31.2',
    '; BambuStudio 1.8',
  ].join('\n');
  const r = parseGcodeText(txt);
  assert.equal(r.printTimeMins, 64, '1h4m5s -> 64 min');
  assert.equal(r.filamentGrams, 31.2);
  assert.equal(r.slicer, 'BambuStudio');
});

test('OrcaSlicer colon separators', () => {
  const txt = [
    '; OrcaSlicer 2.0',
    '; estimated printing time (normal mode) = 0h 45m 0s',
    '; filament used [g] : 8.0',
  ].join('\n');
  const r = parseGcodeText(txt);
  assert.equal(r.printTimeMins, 45);
  assert.equal(r.filamentGrams, 8.0);
  assert.equal(r.slicer, 'OrcaSlicer');
});

test('head+tail concatenation parses a summary located only in the tail', () => {
  const head = ';FLAVOR:Marlin\nG28\nG1 X0 Y0\n';        // movement, no summary
  const tail = '; estimated printing time (normal mode) = 0h 30m 0s\n; filament used [g] = 5.0\n';
  const r = parseGcodeText(head + '\n' + tail);             // mimics the head+tail read
  assert.equal(r.printTimeMins, 30);
  assert.equal(r.filamentGrams, 5.0);
});

test('no metadata → nulls (graceful, never throws)', () => {
  const r = parseGcodeText('G28\nG1 X10 Y10 E5\nG1 X20\n');
  assert.equal(r.printTimeMins, null);
  assert.equal(r.filamentGrams, null);
  assert.equal(r.slicer, null);
});

test('empty / nullish input is safe', () => {
  assert.deepEqual(parseGcodeText(''), { printTimeMins: null, filamentGrams: null, filamentType: null, slicer: null });
  assert.deepEqual(parseGcodeText(null), { printTimeMins: null, filamentGrams: null, filamentType: null, slicer: null });
});

test('parseFilamentType extracts material (first extruder for multi-material)', () => {
  const { parseFilamentType } = require('../lib/gcode-parse.js');
  assert.equal(parseFilamentType('; filament_type = PLA'), 'PLA');
  assert.equal(parseFilamentType('; filament_type : PETG'), 'PETG');
  assert.equal(parseFilamentType('; filament_type = PLA;PETG'), 'PLA', 'first of a multi-material list');
  assert.equal(parseFilamentType('; estimated printing time = 1h'), null, 'no material → null');
  // surfaced on the full parse result
  assert.equal(parseGcodeText('; filament_type = ABS\n; filament used [g] = 5').filamentType, 'ABS');
});

test('detectSlicer recognizes the common slicers', () => {
  assert.equal(detectSlicer('; generated by PrusaSlicer 2.7'), 'PrusaSlicer');
  assert.equal(detectSlicer('; SuperSlicer 2.5'), 'SuperSlicer');
  assert.equal(detectSlicer('; Cura_SteamEngine 5.4'), 'Cura');
});
