/**
 * POST /api/intake/estimate — pricing a model a stranger uploaded.
 *
 * This is the only route in Khayt that hands a price to someone who is not the
 * shop, and the only public one that accepts a body measured in megabytes. So
 * these tests boot the real server and speak HTTP to it: asserting against
 * lib/public-quote.js directly would prove the arithmetic (already covered) and
 * nothing about the auth, the limits, or what happens when the body is hostile.
 */
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const { registerLanServer } = require(path.join(ROOT, 'lib/lan-server.js'));
const { writeZip } = require(path.join(ROOT, 'lib/zip-write.js'));

const PORT = 3994;
const PIN = '4321';
const BASE = `http://127.0.0.1:${PORT}`;
const handlers = new Map();
const noop = () => {};

const PRESET = {
  id: 'P1', name: 'A1', wearRate: 0.75, powerDraw: 150, elecRate: 0.18,
  laborRate: 90, failureRate: 10, prepTime: 0.25, postTime: 0.5,
};

const baseStore = () => ({
  inventory: [],
  printers: [PRESET],
  settings: {
    currency: 'SAR',
    lanApi: {
      intakeToken: 'tok',
      intakeQuote: {
        enabled: true, presetId: 'P1', spoolCost: 90, spoolWeight: 1000,
        marginPct: 40, wastePct: 0.03,
        // Raised so the suite's own traffic does not trip the public limit;
        // the limit itself is proven in its own test below.
        hourlyLimit: 500,
      },
    },
  },
  printLog: [], machines: [], clients: [], waitingList: [], tombstones: [],
});

let store = baseStore();

before(async () => {
  registerLanServer({
    fs,
    ipcMain: { handle: (n, f) => handlers.set(n, f) },
    BrowserWindow: class { static getAllWindows() { return []; } },
    safeJsonParse: (s, f) => { try { return JSON.parse(s); } catch { return f; } },
    syncLanServerStoreFromDisk: noop,
    resolveStoreSecret: (v) => v,
    isStoreSecretMasked: () => false,
    migrateLanApiSecrets: noop,
    ensureLanIntakeToken: () => ({ token: 'tok', generated: false }),
    ensureLanIntakePin: () => ({ pin: '1234', generated: false }),
    ensureLanCalendarToken: () => ({ token: 'cal', generated: false }),
    writeStoreToDisk: async () => {},
    persistLanStoreUpdate: async (s) => { store = s; },
    getLanServerStore: () => store,
    setLanServerStore: (s) => { store = s; },
    getMainWindow: () => null,
    statusPagesDir: path.join(ROOT, 'status-pages'),
    appRoot: ROOT,
    getPrinterStatusCache: () => ({}),
  });
  const r = await handlers.get('hub:start-lan-server')(null, { port: PORT, pin: PIN, bindLan: 'loopback' });
  assert.ok(r && r.ok, `server did not start: ${JSON.stringify(r)}`);
});

after(async () => {
  const stop = handlers.get('hub:stop-lan-server');
  if (stop) await stop(null, {});
});

const PRUSA_CFG = [
  '; generated by PrusaSlicer 2.8.0',
  '; estimated printing time (normal mode) = 3h 12m 40s',
  '; filament used [g] = 41.83',
  '; filament_type = PLA',
].join('\n');

const TETRA = '<?xml version="1.0"?><model unit="millimeter"><resources>'
  + '<object id="1" type="model"><mesh><vertices>'
  + '<vertex x="0" y="0" z="0"/><vertex x="60" y="0" z="0"/>'
  + '<vertex x="0" y="60" z="0"/><vertex x="0" y="0" z="60"/>'
  + '</vertices><triangles>'
  + '<triangle v1="0" v2="2" v3="1"/><triangle v1="0" v2="1" v3="3"/>'
  + '<triangle v1="0" v2="3" v3="2"/><triangle v1="1" v2="2" v3="3"/>'
  + '</triangles></mesh></object></resources>'
  + '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build></model>';

const slicedZip = () => writeZip([
  { name: '3D/3dmodel.model', data: Buffer.from(TETRA, 'utf8') },
  { name: 'Metadata/Slic3r_PE.config', data: Buffer.from(PRUSA_CFG, 'utf8') },
]);
const unslicedZip = () => writeZip([{ name: '3D/3dmodel.model', data: Buffer.from(TETRA, 'utf8') }]);

/** POST a model. Authenticates with the intake token, as the form's session does. */
const estimate = (name, body, opts = {}) => fetch(
  `${BASE}/api/intake/estimate?name=${encodeURIComponent(name)}${opts.qty ? `&qty=${opts.qty}` : ''}`,
  {
    method: 'POST',
    headers: {
      'content-type': 'application/octet-stream',
      ...(opts.noAuth ? {} : { 'x-khayt-intake-token': 'tok' }),
    },
    body,
  });

test('a sliced model comes back priced, and named as the slicer\'s figures', async () => {
  const r = await estimate('part.3mf', slicedZip());
  assert.equal(r.status, 200);
  const b = await r.json();
  assert.equal(b.ok, true, JSON.stringify(b));
  assert.equal(b.exact, true);
  assert.equal(b.slicer, 'PrusaSlicer');
  assert.ok(b.price > 0);
  assert.equal(b.currency, 'SAR');
  assert.ok(b.ref, 'a reference is issued so the submission can cite it');
  assert.equal(b.binding, false, 'and it is never a binding quote');
  // 41.83 g plus the shop's 3% waste.
  assert.ok(Math.abs(b.grams - 41.83 * 1.03) < 0.2, `grams was ${b.grams}`);
});

test('an unsliced model is priced but flagged as an estimate', async () => {
  const b = await (await estimate('raw.3mf', unslicedZip())).json();
  assert.equal(b.ok, true, JSON.stringify(b));
  assert.equal(b.exact, false);
  assert.equal(b.slicer, null, 'no slicer produced this');
  assert.ok(b.price > 0);
});

test('the route is off unless the shop switched it on — and refuses BEFORE reading the body', async () => {
  store.settings.lanApi.intakeQuote.enabled = false;
  try {
    const r = await estimate('part.3mf', slicedZip());
    assert.equal(r.status, 403, 'a closed door, not a 200 with a sad message');
    const b = await r.json();
    assert.equal(b.ok, false);
    assert.equal(b.reason, 'off');
    assert.equal(b.price, undefined, 'no number leaks from a refusal');
  } finally {
    store.settings.lanApi.intakeQuote.enabled = true;
  }
});

test('it needs an intake session or token, like the intake submit does', async () => {
  const r = await estimate('part.3mf', slicedZip(), { noAuth: true });
  assert.equal(r.status, 401);
});

test('only model extensions are accepted', async () => {
  for (const name of ['notes.txt', 'x.exe', 'a.php', 'no-extension', '../../etc/passwd']) {
    const b = await (await estimate(name, Buffer.from('hello'))).json();
    assert.equal(b.ok, false, name);
    assert.equal(b.reason, 'unsupported', name);
  }
});

test('an unreadable file is refused without a price', async () => {
  const b = await (await estimate('broken.3mf', Buffer.from('not a zip'))).json();
  assert.equal(b.ok, false);
  assert.ok(['no-numbers', 'no-price'].includes(b.reason), b.reason);
  assert.equal(b.price, undefined);
});

test('an empty body is refused as a bad request, not priced', async () => {
  const r = await estimate('empty.stl', Buffer.alloc(0));
  assert.equal(r.status, 400, 'a caller sent nothing — that is their error, not a quote');
  const b = await r.json();
  assert.equal(b.ok, false);
  assert.equal(b.price, undefined);
});

test('an unconfigured shop refuses rather than quoting zero', async () => {
  const saved = store.settings.lanApi.intakeQuote.spoolCost;
  store.settings.lanApi.intakeQuote.spoolCost = 0;
  try {
    const b = await (await estimate('part.3mf', slicedZip())).json();
    assert.equal(b.ok, false);
    assert.equal(b.reason, 'not-configured');
    assert.equal(b.price, undefined);
  } finally {
    store.settings.lanApi.intakeQuote.spoolCost = saved;
  }
});

test('quantity is honoured and bounded', async () => {
  const one = await (await estimate('p.3mf', slicedZip())).json();
  const four = await (await estimate('p.3mf', slicedZip(), { qty: 4 })).json();
  assert.equal(four.qty, 4);
  assert.ok(four.price > one.price);
  const silly = await (await estimate('p.3mf', slicedZip(), { qty: 999999 })).json();
  assert.equal(silly.qty, 1000, 'clamped');
});

test('the estimate attached to a submitted request is the SERVER\'s, not the browser\'s', async () => {
  // A browser can post any number it likes. The shop must see what we actually
  // said, so the submission cites a reference and we look it up.
  const est = await (await estimate('part.3mf', slicedZip())).json();
  assert.ok(est.ok && est.ref);

  const before = store.waitingList.length;
  const r = await fetch(`${BASE}/api/intake`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-khayt-intake-token': 'tok' },
    body: JSON.stringify({
      name: 'A Customer', description: 'Please print this bracket', consent: true,
      estimateRef: est.ref,
      // The lie a hostile browser would tell:
      estValue: 999999, modelQuote: { price: 1, exact: true },
    }),
  });
  assert.equal(r.status, 200, await r.text());
  assert.equal(store.waitingList.length, before + 1);
  const entry = store.waitingList[store.waitingList.length - 1];
  assert.equal(entry.estValue, est.price, 'our figure, not theirs');
  assert.equal(entry.modelQuote.price, est.price);
  assert.equal(entry.modelQuote.exact, true);
  assert.equal(entry.modelQuote.binding, false);
});

test('a forged or stale reference attaches nothing at all', async () => {
  const before = store.waitingList.length;
  const r = await fetch(`${BASE}/api/intake`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-khayt-intake-token': 'tok' },
    body: JSON.stringify({
      name: 'B Customer', description: 'No estimate was ever issued', consent: true,
      estimateRef: 'est_made_up', estValue: 500000,
    }),
  });
  assert.equal(r.status, 200);
  const entry = store.waitingList[store.waitingList.length - 1];
  assert.equal(store.waitingList.length, before + 1);
  assert.equal(entry.estValue, 0, 'an unrecognised reference prices nothing');
  assert.equal(entry.modelQuote, undefined);
});

test('a request with no model at all still submits fine', async () => {
  // The upload is optional; the form must keep working exactly as it did.
  const r = await fetch(`${BASE}/api/intake`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-khayt-intake-token': 'tok' },
    body: JSON.stringify({ name: 'C', description: 'Just a question', consent: true }),
  });
  assert.equal(r.status, 200);
  const entry = store.waitingList[store.waitingList.length - 1];
  assert.equal(entry.clientName, 'C');
  assert.equal(entry.modelQuote, undefined);
});

test('the intake page offers the upload only when quoting is on', async () => {
  const on = await (await fetch(`${BASE}/intake`)).text();
  assert.match(on, /id="modelFile"/, 'the field is there when enabled');
  assert.match(on, /not stored/, 'and says the file is not kept');

  store.settings.lanApi.intakeQuote.enabled = false;
  try {
    const off = await (await fetch(`${BASE}/intake`)).text();
    assert.ok(!/id="modelFile"/.test(off), 'and absent when disabled');
  } finally {
    store.settings.lanApi.intakeQuote.enabled = true;
  }
});

test('an oversized body is cut off rather than buffered', async () => {
  // 32 MB cap. Sending 40 MB must not be held in memory to completion.
  const big = Buffer.alloc(40 * 1024 * 1024, 0x41);
  let status = 0;
  try {
    const r = await estimate('huge.stl', big);
    status = r.status;
  } catch (e) {
    // A destroyed socket surfaces as a fetch failure, which is the intended
    // outcome — the point is that it did not succeed.
    status = 413;
  }
  assert.ok(status === 413 || status >= 400, `expected a refusal, got ${status}`);
});

test('a visitor who hammers the endpoint is rate limited', async () => {
  // Each request parses a mesh, so this is the guard that stops one visitor
  // pinning the shop's machine.
  const saved = store.settings.lanApi.intakeQuote.hourlyLimit;
  store.settings.lanApi.intakeQuote.hourlyLimit = 1;
  try {
    // The window counter is shared with the rest of the suite, so the very next
    // request is already over a limit of one.
    const r = await estimate('part.3mf', slicedZip());
    assert.equal(r.status, 429);
    const b = await r.json();
    assert.match(b.error, /Too many/);
  } finally {
    store.settings.lanApi.intakeQuote.hourlyLimit = saved;
  }
});

/**
 * Concurrency, which the hourly limit does not bound.
 *
 * The per-IP hourly limit answers "how often", never "how many at once", and
 * the two are not the same bound: twenty simultaneous uploads is 640 MB held in
 * the main process while every one of them is still inside its allowance. It is
 * also the only one of the three limits on this route that a caller cannot move,
 * because it is keyed on nothing — behind the tunnel the per-IP key is the
 * caller's own X-Forwarded-For header.
 */
test('only so many uploads may be in flight at once, and a slot comes back', async () => {
  const http = require('node:http');
  // Announce a body far larger than we send, so the server sits waiting for the
  // rest and the slot stays taken while we probe.
  const holdOpen = () => new Promise((resolve) => {
    const req = http.request({
      host: '127.0.0.1', port: PORT, method: 'POST',
      path: '/api/intake/estimate?name=held.stl',
      headers: {
        'content-type': 'application/octet-stream',
        'x-khayt-intake-token': 'tok',
        'content-length': '4096',
      },
    });
    req.on('error', () => {});
    req.write(Buffer.alloc(16, 0x41), () => resolve(req));
  });

  const held = [];
  for (let i = 0; i < 3; i++) held.push(await holdOpen());
  try {
    // Poll rather than assume the three are parked: the writes have flushed but
    // the server reaching the slot check is a separate turn of the loop.
    let res = null;
    for (let i = 0; i < 40 && !(res && res.status === 503); i++) {
      res = await estimate('probe.stl', Buffer.alloc(64, 0x41));
      if (res.status !== 503) await new Promise((r) => setTimeout(r, 25));
    }
    assert.equal(res.status, 503, 'a fourth concurrent upload should be turned away');
    const b = await res.json();
    assert.equal(b.reason, 'busy');
    assert.equal(b.price, undefined, 'and a refusal still leaks no number');
  } finally {
    for (const r of held) r.destroy();
  }

  // Slots are released on response close, including the sockets we just killed
  // mid-upload — otherwise one abandoned upload would retire a slot for good.
  let after = null;
  for (let i = 0; i < 40; i++) {
    after = await estimate('part.3mf', slicedZip());
    if (after.status === 200) break;
    await new Promise((r) => setTimeout(r, 25));
  }
  assert.equal(after.status, 200, 'an abandoned upload must not retire its slot permanently');
});

/*
 * Break-risk on a stranger's upload.
 *
 * This is the placement where the triage is worth most: the shop is deciding
 * whether to take a job at a price a customer has ALREADY been shown, and "a
 * fifth of this needs supports" is exactly what turns an acceptable price into
 * an unacceptable one.
 *
 * And it is the placement where the answer must not go back out. The visitor
 * gets a price. Whether the model needs supports is the shop's call, not an
 * argument to have with someone who cannot act on it — so the reply to the
 * browser stays exactly as it was.
 */

/** A binary STL of a cube held up over a small pad: a real 100 mm² ceiling. */
function bridgeStl() {
  const tri = (a, b, c) => [a, b, c];
  const boxTris = (x0, y0, z0, x1, y1, z1) => {
    const v = [
      [x0, y0, z0], [x1, y0, z0], [x1, y1, z0], [x0, y1, z0],
      [x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1],
    ];
    const q = (a, b, c, d) => [tri(v[a], v[b], v[c]), tri(v[a], v[c], v[d])];
    return [...q(0, 3, 2, 1), ...q(4, 5, 6, 7), ...q(0, 1, 5, 4),
            ...q(2, 3, 7, 6), ...q(1, 2, 6, 5), ...q(0, 4, 7, 3)];
  };
  const tris = [...boxTris(0, 0, 0, 2, 2, 1), ...boxTris(0, 0, 8, 10, 10, 10)];
  const buf = Buffer.alloc(84 + tris.length * 50);
  buf.writeUInt32LE(tris.length, 80);
  let off = 84;
  for (const t of tris) {
    off += 12;                                   // normal, which parseStl ignores
    for (const p of t) for (const n of p) { buf.writeFloatLE(n, off); off += 4; }
    off += 2;                                    // attribute bytes
  }
  return buf;
}

test('a customer upload is analysed for the shop, and the visitor is told only the price', async () => {
  const res = await estimate('part.stl', bridgeStl());
  const body = await res.json();
  assert.equal(body.ok, true, JSON.stringify(body));
  assert.ok(body.price > 0);
  // The whole point: nothing about the mesh comes back out.
  assert.equal(body.risk, undefined, 'the print-risk report was sent to the visitor');
  assert.deepEqual(
    Object.keys(body).sort(),
    ['binding', 'currency', 'exact', 'grams', 'hours', 'ok', 'price', 'qty', 'ref', 'slicer'].sort(),
    'the public reply grew a field — anything added here is visible to strangers',
  );

  // …and the shop sees it when the request lands in front of them.
  const before = store.waitingList.length;
  const r = await fetch(`${BASE}/api/intake`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-khayt-intake-token': 'tok' },
    body: JSON.stringify({
      name: 'A Customer', description: 'Print this please', consent: true, estimateRef: body.ref,
    }),
  });
  assert.equal(r.status, 200, await r.text());
  assert.equal(store.waitingList.length, before + 1);

  const entry = store.waitingList[store.waitingList.length - 1];
  const risk = entry.modelQuote && entry.modelQuote.risk;
  assert.ok(risk, 'the shop was given no triage for a model with a 100 mm² ceiling');
  const ids = risk.risks.map((x) => x.id);
  assert.ok(ids.includes('overhang'), `expected an overhang finding, got ${JSON.stringify(ids)}`);
  assert.ok(ids.includes('bridge'), 'a flat ceiling was not reported as a bridge');
  // The measurement travels with it, or the shop cannot judge it.
  const over = risk.risks.find((x) => x.id === 'overhang');
  assert.ok(over.fraction > 0, 'the finding arrived without its measurement');
  assert.equal(over.thresholdDeg, 45);
});

test('a request with no model attaches no risk, rather than an empty one', async () => {
  const before = store.waitingList.length;
  const r = await fetch(`${BASE}/api/intake`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-khayt-intake-token': 'tok' },
    body: JSON.stringify({ name: 'B Customer', description: 'Just asking', consent: true }),
  });
  assert.equal(r.status, 200);
  assert.equal(store.waitingList.length, before + 1);
  const entry = store.waitingList[store.waitingList.length - 1];
  assert.equal(entry.modelQuote, undefined, 'a request with no model grew a quote');
});
