/**
 * Running a 3MF conversion somewhere the UI is not waiting on it.
 *
 * lib/mf-convert.js is synchronous CPU work and was called straight from an
 * ipcMain handler. Measured on a real 229 MB six-colour project, a retarget to
 * a Snapmaker U1 took 377.9 s — six minutes with the main process unable to
 * turn a menu, close a window or answer another IPC call, and macOS reporting
 * the app as not responding. A shop watching that force-quits, which looks
 * exactly like the conversion being broken.
 *
 * These tests are about the HARNESS, not the conversion: that the work leaves
 * the calling thread, that every failure still answers, and that a worker is
 * never left holding a few hundred megabytes.
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { runMf, WORKER } = require('../lib/mf-offload.js');
const { writeZip } = require('../lib/zip-write.js');

const tiny3mf = () => writeZip([
  { name: '3D/3dmodel.model', data: Buffer.from('<?xml version="1.0"?><model unit="millimeter"><resources/></model>', 'utf8') },
  { name: 'Metadata/slice_info.config', data: Buffer.from('; generated by OrcaSlicer', 'utf8') },
]);

test('the worker file that gets spawned actually exists', () => {
  // A packaged build keeps lib/ inside app.asar, where `new Worker()` cannot
  // open it — build.asarUnpack and the path rewrite in mf-offload exist for
  // that, and this is the cheap check that the resolved path is real.
  assert.ok(fs.existsSync(WORKER), `worker missing at ${WORKER}`);
  assert.equal(path.basename(WORKER), 'mf-worker.js');
});

test('an analyse comes back with the same answer it would have given inline', async () => {
  const buf = tiny3mf();
  const inline = require('../lib/mf-convert.js').analyze(Buffer.from(buf));
  const viaWorker = await runMf('analyze', Buffer.from(buf));
  assert.equal(viaWorker.ok, inline.ok);
  assert.equal(viaWorker.flavour, inline.flavour, 'the worker must not change the verdict');
});

test('the calling thread keeps running while the work happens', async () => {
  // The entire point. A blocked thread cannot fire a timer, so a tick count of
  // zero is what the old inline call would have produced.
  let ticks = 0;
  const iv = setInterval(() => { ticks++; }, 5);
  await runMf('analyze', tiny3mf());
  clearInterval(iv);
  assert.ok(ticks > 0, 'the caller was blocked — the work did not leave the thread');
});

test('an unknown operation answers instead of hanging', async () => {
  const r = await runMf('sharpen', tiny3mf());
  assert.equal(r.ok, false);
  assert.match(r.error, /unknown op/i);
});

test('a worker that will not start still produces an answer', async () => {
  // Every failure has to settle the promise. A caller awaiting a conversion
  // that never resolves leaves the button disabled and the modal stuck open.
  const r = await runMf('analyze', tiny3mf(), {}, {
    Worker: class { constructor() { throw new Error('EMFILE: too many open files'); } },
  });
  assert.equal(r.ok, false);
  assert.match(r.error, /EMFILE/);
});

test('a worker killed mid-job is reported, not waited on forever', async () => {
  // The OS kills workers under memory pressure, and a 229 MB job invites it.
  const { EventEmitter } = require('events');
  class Killed extends EventEmitter {
    constructor() { super(); setImmediate(() => this.emit('exit', 9)); }
    terminate() {}
  }
  const r = await runMf('convert', tiny3mf(), {}, { Worker: Killed });
  assert.equal(r.ok, false);
  assert.match(r.error, /exit 9/);
});

test('a job that never answers times out rather than stalling the app', async () => {
  const { EventEmitter } = require('events');
  let terminated = false;
  class Silent extends EventEmitter {
    terminate() { terminated = true; }
  }
  const r = await runMf('convert', tiny3mf(), {}, { Worker: Silent, timeoutMs: 40 });
  assert.equal(r.ok, false);
  assert.match(r.error, /timed out/i);
  assert.ok(terminated, 'a timed-out worker must be torn down, not left holding the file');
});

test('a late reply after a timeout leaves the answer alone', async () => {
  // Note what this does and does not prove. Promise resolution is idempotent,
  // so the answer survives a late message whether or not mf-offload guards for
  // it — removing that guard leaves this test passing, and it is recorded as
  // an equivalent mutant rather than pretended to be covered. What IS worth
  // pinning is the observable behaviour: a job that outruns its timeout is
  // reported as timed out and stays that way.
  const { EventEmitter } = require('events');
  class Late extends EventEmitter {
    constructor() { super(); setTimeout(() => this.emit('message', { ok: true, result: { ok: true, late: true } }), 60); }
    terminate() {}
  }
  const r = await runMf('convert', tiny3mf(), {}, { Worker: Late, timeoutMs: 20 });
  assert.match(r.error, /timed out/i);
  await new Promise((res) => setTimeout(res, 80));
  assert.match(r.error, /timed out/i, 'the late message rewrote a settled answer');
});
