/**
 * Deciding what a dropped file actually tells us.
 *
 * The load-bearing assertion in this file is not a number — it is `exact`. A
 * slicer's output is what the printer is about to do; a geometric estimate can
 * be out by a large factor on a sparse or heavily-supported part. A quote that
 * cannot tell those apart is worse than no quote, so every test that produces a
 * number also pins down which KIND of number it is.
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { intake, SUPPORTED, extOf } = require('../lib/model-intake.js');
const { writeZip } = require('../lib/zip-write.js');
const { parseObj } = require('../lib/obj-parse.js');

const CUBE_OBJ = `v 0 0 0
v 20 0 0
v 20 20 0
v 0 20 0
v 0 0 20
v 20 0 20
v 20 20 20
v 0 20 20
f 1 4 3
f 1 3 2
f 5 6 7
f 5 7 8
f 1 2 6
f 1 6 5
f 2 3 7
f 2 7 6
f 3 4 8
f 3 8 7
f 4 1 5
f 4 5 8
`;

const PRUSA_CFG = [
  '; generated by PrusaSlicer 2.8.0 on 2026-07-31',
  '; estimated printing time (normal mode) = 3h 12m 40s',
  '; filament used [g] = 41.83',
  '; filament_type = PLA',
  '; total filament cost = 1.26',
].join('\n');

/** A 20mm tetrahedron as a 3MF mesh — volume 20·20·20/6. */
const TETRA_MODEL = '<?xml version="1.0"?><model unit="millimeter"><resources>'
  + '<object id="1" type="model"><mesh><vertices>'
  + '<vertex x="0" y="0" z="0"/><vertex x="20" y="0" z="0"/>'
  + '<vertex x="0" y="20" z="0"/><vertex x="0" y="0" z="20"/>'
  + '</vertices><triangles>'
  + '<triangle v1="0" v2="2" v3="1"/><triangle v1="0" v2="1" v3="3"/>'
  + '<triangle v1="0" v2="3" v3="2"/><triangle v1="1" v2="2" v3="3"/>'
  + '</triangles></mesh></object></resources>'
  + '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build></model>';

const zip = (members) => writeZip(members.map((m) => ({ name: m[0], data: Buffer.from(m[1], 'utf8') })));
const stlOf = (objText) => {
  const tris = parseObj(objText, { keepTriangles: true }).triangles;
  const b = Buffer.alloc(84 + tris.length * 50);
  b.writeUInt32LE(tris.length, 80);
  let o = 84;
  for (const t of tris) { o += 12; for (const v of t) for (const c of v) { b.writeFloatLE(c, o); o += 4; } o += 2; }
  return b;
};

test('a gcode file reports the slicer\'s own numbers as exact', () => {
  const r = intake({ filename: 'part.gcode', bytes: PRUSA_CFG });
  assert.equal(r.source, 'slicer');
  assert.equal(r.exact, true, 'the slicer computed this, it is not a guess');
  assert.equal(r.printTimeMins, 192 + 1);        // 3h 12m 40s → 193 min
  assert.equal(r.filamentGrams, 41.83);
  assert.equal(r.filamentType, 'PLA');
  assert.equal(r.filamentCost, 1.26);
  assert.equal(r.slicer, 'PrusaSlicer');
  assert.equal(r.geometry, null, 'no mesh was read, and none is claimed');
});

test('a sliced 3MF is UNZIPPED — its metadata is compressed, not lying in the bytes', () => {
  // This is the whole wedge. Reading a 3MF as raw text finds nothing for any
  // normally-written project, because every member is DEFLATE'd.
  const buf = zip([['3D/3dmodel.model', TETRA_MODEL], ['Metadata/Slic3r_PE.config', PRUSA_CFG]]);
  assert.ok(!buf.toString('latin1').includes('filament used'), 'the text really is not in the raw bytes');

  const r = intake({ filename: 'project.3mf', bytes: buf });
  assert.equal(r.source, 'slicer');
  assert.equal(r.exact, true);
  assert.equal(r.printTimeMins, 193);
  assert.equal(r.filamentGrams, 41.83);
  assert.equal(r.slicer, 'PrusaSlicer');
});

test('a Bambu/Orca 3MF reports slice_info time and summed filament', () => {
  const slice = '<config><plate><metadata key="prediction" value="7200"/>'
    + '<filament id="1" used_g="25.5"/><filament id="2" used_g="10.0"/></plate></config>';
  const r = intake({ filename: 'b.3mf', bytes: zip([['3D/3dmodel.model', TETRA_MODEL], ['Metadata/slice_info.config', slice]]) });
  assert.equal(r.source, 'slicer');
  assert.equal(r.exact, true);
  assert.equal(r.printTimeMins, 120, '7200 s → 120 min');
  assert.equal(r.filamentGrams, 35.5, 'both filaments, added up');
});

test('an embedded .gcode member beats a config member', () => {
  // A "sliced 3MF" carries the real toolpath; if both are present the gcode is
  // the more authoritative of the two.
  const other = '; estimated printing time (normal mode) = 1h 0m 0s\n; filament used [g] = 5\n';
  const r = intake({ filename: 's.3mf', bytes: zip([
    ['Metadata/Slic3r_PE.config', other],
    ['Metadata/plate_1.gcode', PRUSA_CFG],
  ]) });
  assert.equal(r.printTimeMins, 193, 'the gcode member won');
  assert.equal(r.filamentGrams, 41.83);
});

test('an UNSLICED 3MF falls back to geometry and says so', () => {
  const r = intake({ filename: 'raw.3mf', bytes: zip([['3D/3dmodel.model', TETRA_MODEL]]) });
  assert.equal(r.source, 'geometry');
  assert.equal(r.exact, false, 'nothing sliced this — the numbers are assumptions');
  assert.equal(r.printTimeMins, null, 'and no time is invented');
  assert.equal(r.filamentGrams, null);
  assert.ok(Math.abs(r.geometry.volumeMm3 - 8000 / 6) < 1e-6);
  assert.deepEqual(
    { x: r.geometry.bbox.x, y: r.geometry.bbox.y, z: r.geometry.bbox.z },
    { x: 20, y: 20, z: 20 });
});

test('STL and OBJ are geometry, never exact', () => {
  for (const [name, bytes] of [['c.stl', stlOf(CUBE_OBJ)], ['c.obj', CUBE_OBJ]]) {
    const r = intake({ filename: name, bytes });
    assert.equal(r.source, 'geometry', name);
    assert.equal(r.exact, false, name);
    assert.equal(r.printTimeMins, null, name);
    assert.equal(r.filamentGrams, null, name);
    assert.equal(r.geometry.volumeMm3, 8000, name);
  }
});

test('the same solid weighs the same whichever format it arrives in', () => {
  // A customer sending .obj instead of .stl must not get a different price.
  const a = intake({ filename: 'c.stl', bytes: stlOf(CUBE_OBJ) });
  const b = intake({ filename: 'c.obj', bytes: CUBE_OBJ });
  assert.equal(a.geometry.volumeMm3, b.geometry.volumeMm3);
  assert.deepEqual(a.geometry.bbox.max, b.geometry.bbox.max);
});

test('a gcode with no summary is reported as such, not as zero', () => {
  // "0 minutes, 0 grams" priced as a real job is a free print.
  const r = intake({ filename: 'x.gcode', bytes: 'G28\nG1 X10 Y10 E5\nG1 X20\n' });
  assert.equal(r.exact, false);
  assert.equal(r.source, null);
  assert.equal(r.printTimeMins, null);
  assert.ok(r.warnings.includes('no-slicer-summary'));
});

test('a half-answer is not treated as an answer', () => {
  // Time without weight (or the reverse) cannot price a job, so it must not be
  // labelled exact — otherwise the missing half silently reads as zero.
  const timeOnly = intake({ filename: 'a.gcode', bytes: '; estimated printing time (normal mode) = 2h 0m 0s\n' });
  assert.equal(timeOnly.exact, false);
  assert.equal(timeOnly.printTimeMins, 120, 'the half we do have is still reported');
  assert.equal(timeOnly.filamentGrams, null);

  const gramsOnly = intake({ filename: 'a.gcode', bytes: '; filament used [g] = 10\n' });
  assert.equal(gramsOnly.exact, false);
  assert.equal(gramsOnly.filamentGrams, 10);
});

test('a 3MF whose slicer data is a half-answer falls through to geometry', () => {
  const partial = '; estimated printing time (normal mode) = 2h 0m 0s\n';   // no grams
  const r = intake({ filename: 'p.3mf', bytes: zip([['3D/3dmodel.model', TETRA_MODEL], ['Metadata/Slic3r_PE.config', partial]]) });
  assert.equal(r.exact, false);
  assert.equal(r.source, 'geometry', 'a usable mesh beats an unusable summary');
  assert.ok(r.geometry.volumeMm3 > 0);
});

test('unsupported and empty input are refused, not guessed', () => {
  const un = intake({ filename: 'notes.txt', bytes: 'hello' });
  assert.equal(un.source, null);
  assert.ok(un.warnings.includes('unsupported'));

  for (const bytes of ['', Buffer.alloc(0), null, undefined]) {
    const r = intake({ filename: 'a.stl', bytes });
    assert.equal(r.source, null, String(bytes));
    assert.ok(r.warnings.includes('empty'));
  }
  assert.equal(intake({}).source, null);
  assert.doesNotThrow(() => intake(null));
});

test('a corrupt file yields a warning, never a throw and never a number', () => {
  // These arrive from customers and from disk. A crash in the calculator is a
  // worse outcome than "we could not read that".
  const notAZip = intake({ filename: 'broken.3mf', bytes: Buffer.from('this is not a zip at all') });
  assert.equal(notAZip.source, null);
  assert.equal(notAZip.exact, false);
  assert.ok(notAZip.warnings.length > 0);

  const truncatedStl = intake({ filename: 'short.stl', bytes: Buffer.from([1, 2, 3, 4, 5]) });
  assert.equal(truncatedStl.exact, false);
  assert.ok(truncatedStl.geometry === null || truncatedStl.geometry.volumeMm3 === 0);
});

test('a 3MF with neither slicer data nor a mesh reports no-geometry', () => {
  const r = intake({ filename: 'empty.3mf', bytes: zip([['3D/3dmodel.model', '<model/>']]) });
  assert.equal(r.source, null);
  assert.equal(r.exact, false);
  assert.ok(r.warnings.includes('no-geometry'));
});

test('extension handling is case-insensitive and lists what it supports', () => {
  assert.equal(extOf('A.STL'), 'stl');
  assert.equal(extOf('a.tar.3MF'), '3mf');
  assert.equal(extOf('noextension'), '');
  assert.equal(intake({ filename: 'C.OBJ', bytes: CUBE_OBJ }).source, 'geometry');
  for (const e of ['gcode', 'gco', '3mf', 'stl', 'obj']) assert.ok(SUPPORTED.includes(e), e);
});

test('exact is never true without both numbers present', () => {
  // The invariant the UI relies on to decide whether to warn.
  const cases = [
    intake({ filename: 'a.gcode', bytes: PRUSA_CFG }),
    intake({ filename: 'a.3mf', bytes: zip([['Metadata/Slic3r_PE.config', PRUSA_CFG]]) }),
    intake({ filename: 'a.stl', bytes: stlOf(CUBE_OBJ) }),
    intake({ filename: 'a.obj', bytes: CUBE_OBJ }),
    intake({ filename: 'a.gcode', bytes: 'G28\n' }),
  ];
  for (const r of cases) {
    if (r.exact) {
      assert.ok(r.printTimeMins > 0 && r.filamentGrams > 0, 'exact implies both numbers');
      assert.equal(r.source, 'slicer', 'exact implies a slicer produced it');
    } else {
      assert.notEqual(r.source, 'slicer', 'a slicer result that is not exact should not claim to be one');
    }
  }
});

/* A 3MF IS MEASURED WITHOUT BEING BUILT.
 *
 * Reading one used to go through extractTriangles, which materialises twice —
 * resolve() memoises each object's geometry and emit() builds a second
 * transformed copy — so a real 229 MB poster of 13.2M facets wanted about
 * 10 GB. A shop's files are exactly that shape and none of them are sliced, so
 * the mesh is the only place their volume and size can come from.
 *
 * mf-convert measureMesh folds each facet into a running total instead, holding
 * vertices in a Float64Array and indices in a Uint32Array; its numbers are
 * asserted equal to the building path in test/mf-measure-mesh.test.js. What is
 * pinned HERE is that the intake actually uses it, and that the one caller who
 * still needs the triangles — the overhang report — is the only one who pays.
 */
test('measuring a 3MF does not build its triangles', () => {
  const zip = require('../lib/zip-write.js');
  const bytes = zip.writeZip([
    { name: '3D/3dmodel.model', data: Buffer.from(
      '<model unit="millimeter"><resources><object id="1" type="model"><mesh>'
      + '<vertices><vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/><vertex x="0" y="10" z="0"/><vertex x="0" y="0" z="10"/></vertices>'
      + '<triangles><triangle v1="0" v2="1" v3="2"/><triangle v1="0" v2="1" v3="3"/>'
      + '<triangle v1="0" v2="2" v3="3"/><triangle v1="1" v2="2" v3="3"/></triangles>'
      + '</mesh></object></resources><build><item objectid="1"/></build></model>') },
  ]);

  const mf = require('../lib/mf-convert.js');
  const realExtract = mf.extractTriangles;
  let built = 0;
  mf.extractTriangles = (...a) => { built++; return realExtract(...a); };
  try {
    const r = intake({ filename: 'tetra.3mf', bytes }, { risk: false });
    assert.equal(r.source, 'geometry');
    assert.equal(r.geometry.triangleCount, 4, 'it was measured');
    assert.ok(r.geometry.volumeMm3 > 0, 'and the volume is real');
    assert.equal(built, 0, 'the triangles were built anyway — that is the whole cost this avoids');
  } finally {
    mf.extractTriangles = realExtract;
  }
});

test('the overhang report is the only reader that still pays for triangles', () => {
  const zip = require('../lib/zip-write.js');
  const bytes = zip.writeZip([
    { name: '3D/3dmodel.model', data: Buffer.from(
      '<model unit="millimeter"><resources><object id="1" type="model"><mesh>'
      + '<vertices><vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/><vertex x="0" y="10" z="0"/><vertex x="0" y="0" z="10"/></vertices>'
      + '<triangles><triangle v1="0" v2="1" v3="2"/><triangle v1="0" v2="1" v3="3"/>'
      + '<triangle v1="0" v2="2" v3="3"/><triangle v1="1" v2="2" v3="3"/></triangles>'
      + '</mesh></object></resources><build><item objectid="1"/></build></model>') },
  ]);
  const withRisk = intake({ filename: 'tetra.3mf', bytes }, { risk: true, nozzleDiameter: 0.4 });
  assert.ok(withRisk.risk, 'asking for the report must still get one');
  assert.equal(withRisk.geometry.triangleCount, 4, 'and the measurement is unchanged by asking');
});

test('a 3MF can defer its mesh so the caller can measure it elsewhere', () => {
  // Folding 13M facets is small in memory and not small in time, and this runs
  // in the main process. `deferMesh` is how main hands it to the 3MF worker.
  const zip = require('../lib/zip-write.js');
  const bytes = zip.writeZip([
    { name: '3D/3dmodel.model', data: Buffer.from(
      '<model unit="millimeter"><resources><object id="1" type="model"><mesh>'
      + '<vertices><vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/></vertices>'
      + '<triangles><triangle v1="0" v2="1" v3="2"/></triangles>'
      + '</mesh></object></resources><build><item objectid="1"/></build></model>') },
  ]);
  const r = intake({ filename: 'x.3mf', bytes }, { risk: false, deferMesh: true });
  assert.ok(r.warnings.includes('mesh-deferred'), 'the caller has to know there is work left to do');
  assert.equal(r.geometry, null, 'and must not be handed a half-measurement');
  assert.equal(r.source, 'geometry', 'the KIND of answer is already known — only the numbers are pending');
});

test('counting a 3MF\'s facets does not build them', () => {
  const mf = require('../lib/mf-convert.js');
  assert.equal(typeof mf.countTriangles, 'function',
    'the cheap count is what lets a caller decide before it commits');
  assert.deepEqual(mf.countTriangles([]), 0);
  assert.deepEqual(mf.countTriangles(null), 0, 'a caller with no members must not throw');
});
