'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { extract, extractGcodeThumbnail, extract3mf, normHex } = require('../lib/thumbnail-extract');
const { makeZip } = require('./helpers/make-zip');

test('gcode: picks the largest embedded PNG thumbnail', () => {
  const gcode = [
    '; generated by PrusaSlicer',
    '; thumbnail begin 16x16 8',
    '; aGVsbG8=',
    '; thumbnail end',
    'G1 X0 Y0',
    '; thumbnail begin 32x32 8',
    '; d29ybGQ=',
    '; thumbnail end',
  ].join('\n');
  const t = extractGcodeThumbnail(gcode);
  assert.equal(t.width, 32);
  assert.equal(t.pngBase64, 'd29ybGQ='); // "world" — the bigger block wins
});

test('gcode: no thumbnail → null', () => {
  assert.equal(extractGcodeThumbnail('G1 X0\nG1 Y0\n').pngBase64, null);
  assert.equal(extractGcodeThumbnail('').pngBase64, null);
});

test('gcode: QOI blocks are ignored (not PNG "thumbnail begin")', () => {
  const g = '; thumbnail_QOI begin 48x48 4\n; AAAA\n; thumbnail_QOI end\n';
  assert.equal(extractGcodeThumbnail(g).pngBase64, null);
});

test('3mf: extracts embedded PNG + colours + swap estimate', () => {
  const png = Buffer.from([0x89, 0x50, 0x4e, 0x47, 1, 2, 3, 4]);
  const sliceInfo = `<?xml version="1.0"?>
<config><plate>
  <filament id="1" tray_info_idx="GFA00" type="PLA" color="#ff0000" used_g="12.5" used_m="4.2"/>
  <filament id="2" type="PLA" color="#00FF00" used_g="3.1" used_m="1.0"/>
</plate></config>`;
  const zip = makeZip([
    { name: 'Metadata/thumbnail.png', data: png, method: 0 },
    { name: 'Metadata/slice_info.config', data: sliceInfo, method: 8 },
    { name: '3D/3dmodel.model', data: '<model/>', method: 8 },
  ]);
  const r = extract3mf(zip);
  assert.equal(r.pngBase64, png.toString('base64'));
  assert.equal(r.colors.length, 2);
  assert.equal(r.colors[0].hex, '#FF0000');
  assert.equal(r.colors[0].grams, 12.5);
  assert.equal(r.colors[1].hex, '#00FF00');
  assert.equal(r.swapCount, 1); // 2 colours, single-extruder floor
});

test('3mf: falls back to project_settings filament_colour when no slice_info', () => {
  const proj = '{"filament_colour":["#112233","#445566","#112233"],"other":1}';
  const zip = makeZip([{ name: 'Metadata/project_settings.config', data: proj, method: 8 }]);
  const r = extract3mf(zip);
  assert.deepEqual(r.colors.map((c) => c.hex), ['#112233', '#445566']); // deduped
  assert.equal(r.pngBase64, null);
});

test('3mf: garbage buffer → empty result, no throw', () => {
  const r = extract3mf(Buffer.from('nonsense'));
  assert.equal(r.pngBase64, null);
  assert.deepEqual(r.colors, []);
});

test('extract() dispatches by extension', () => {
  const g = '; thumbnail begin 8x8 4\n; QUJDRA==\n; thumbnail end\n';
  const eg = extract({ ext: 'gcode', text: g });
  assert.equal(eg.pngBase64, 'QUJDRA==');
  assert.equal(eg.source, 'embedded');
  const eNone = extract({ ext: 'stl', buf: Buffer.from('x') });
  assert.equal(eNone.source, null);
});

test('normHex normalises shorthand + strips alpha', () => {
  assert.equal(normHex('#abc'), '#AABBCC');
  assert.equal(normHex('ff8800'), '#FF8800');
  assert.equal(normHex('#11223344'), '#112233');
  assert.equal(normHex('nope'), null);
});
