/**
 * Initial render pass and DOM event wiring.
 */
(function (global) {
/* ============================================================
   Render-everything entry point
   ============================================================ */
function initialRender() {
  applyMode();
  ensureDefaultLocation();
  renderLocationsSettings();
  renderLocationFilter();
  renderPrinterPresets();
  renderJobTemplateSelect();
  renderQuoteTemplates();
  renderMachines();
  renderMachineDropdown();
  renderWaTemplates();
  renderInventory();
  renderConsumables();
  renderSuppliers();
  renderPurchaseOrders();
  renderLogs();
  renderKanban();
  renderAnalytics();
  if (typeof renderReferralAnalytics === 'function') renderReferralAnalytics();
  renderBuild();
  renderCatalog();
  renderClients();
  renderPortfolio();
  renderDashboard();
  renderExpenses();
  checkDueDateNotifications();
  checkRecurringOrders();
  patchRecurringOrdersWithLeadDays();  // Round 12: leadDays-aware auto-clone
  checkRecurringExpenses();
  // Translate any [data-i18n] elements regenerated by the render functions above
  i18n.applyToDom();
  refreshCurrencyLabels();
}


/* ============================================================
   Event wiring
   ============================================================ */
function wireEvents() {
  // Global search
  const btnGs = $('#btnGlobalSearch');
  if (btnGs) btnGs.addEventListener('click', openGlobalSearch);

  // Feature 7 (new 8-pack): Nav switch operator button
  $('#btnNavSwitchOp')?.addEventListener('click', () => openPinPadModal());

  // Help button (Feature 9)
  $('#btnHelp')?.addEventListener('click', openHelpModal);

  // Notification bell
  $('#btnNotifBell')?.addEventListener('click', (e) => {
    e.stopPropagation();
    openNotifPanel();
  });
  // Close notification panel when clicking outside
  document.addEventListener('click', (e) => {
    if (!e.target.closest('#btnNotifBell') && !e.target.closest('#notifPanel')) {
      const panel = $('#notifPanel');
      if (panel) panel.style.display = 'none';
    }
  });

  // Feedback button (header + settings)
  $$('#btnFeedback, #btnFeedbackSettings').forEach(b => b?.addEventListener('click', openFeedbackModal));

  // Extra charge lines (calculator)
  const btnAEL = $('#btnAddExtraLine');
  if (btnAEL) btnAEL.addEventListener('click', () => {
    currentExtraLines.push({ id: uid('EL'), label: '', amount: 0 });
    renderExtraLines();
  });

  // Post-process preset picker in calculator
  const ppPresetRow = $('#ppPresetRow');
  const ppPresetSel = $('#ppPresetSelect');
  if (ppPresetRow && ppPresetSel) {
    const presets = settings.postProcessPresets || [];
    if (presets.length > 0) {
      ppPresetSel.innerHTML = `<option value="">${escapeHtml(t('set.no_presets') || '— select preset —')}</option>`
        + presets.map((p, i) => `<option value="${i}">${escapeHtml(p.name)} (+${fmtMoney(p.amount)})</option>`).join('');
      ppPresetRow.style.display = 'flex';
      ppPresetRow.style.alignItems = 'center';
    }
    $('#btnAddPpPreset')?.addEventListener('click', () => {
      const idx = parseInt(ppPresetSel.value, 10);
      if (isNaN(idx)) return;
      const preset = (settings.postProcessPresets || [])[idx];
      if (!preset) return;
      currentExtraLines.push({ id: uid('EL'), label: preset.name, amount: preset.amount });
      renderExtraLines();
      ppPresetSel.value = '';
    });
  }

  // Batch status move
  $('#btnBatchMove')?.addEventListener('click', batchMoveStatus);
  $('#btnBatchAssignMachine')?.addEventListener('click', batchAssignMachine);
  $('#btnBatchArchive')?.addEventListener('click', batchArchiveOrders);
  $('#showArchivedToggle')?.addEventListener('change', e => {
    showArchivedOrders = e.target.checked;
    renderLogs();
  });

  // Tabs
  $$('.tab-btn').forEach(btn => btn.addEventListener('click', () => switchTab(btn.dataset.tab)));

  // Language select
  $('#langSelect').addEventListener('change', (e) => {
    const lang = e.target.value;
    i18n.set(lang);
    settings.lang = lang;
    // Keep the Settings-tab language dropdown in sync so saveSettingsFromForm()
    // doesn't accidentally revert the language to the old value
    const setLangEl = $('#set_lang');
    if (setLangEl) setLangEl.value = lang;
    saveAll();
    initialRender();
  });

  // Theme toggle
  $('#themeToggle').addEventListener('click', () => {
    const root = document.documentElement;
    const next = root.dataset.theme === 'dark' ? 'light' : 'dark';
    applyTheme(next);
    settings.theme = next;
    saveAll();
    window.KhaytIcon?.hydrateTopbar?.();
  });

  // Calculator
  $('#filamentSelect').addEventListener('change', handleFilamentChange);
  $('#filamentSelect').addEventListener('change', updateFailureRateHint);
  $('#partMachineId')?.addEventListener('change', updateFailureRateHint);
  $$('#calculator-tab input, #calculator-tab select').forEach(el => {
    if (el.id !== 'clientInput' && el.id !== 'printerPreset') el.addEventListener('input', updateGrandTotal);
  });
  // Rush fee checkbox uses 'change' not 'input'
  $('#calcRushFee')?.addEventListener('change', updateGrandTotal);
  $('#btnAddPart').addEventListener('click', addPart);
  $('#btnSaveQuote').addEventListener('click', logPrint);

  // Resin: compute print time & volume from layer parameters
  document.addEventListener('click', (e) => {
    if (e.target.closest('#btnComputeResinTime')) {
      const layers     = Math.max(1, parseInt($('#resinLayers')?.value || '0') || 1);
      const exposure   = Math.max(0, parseFloat($('#resinExposure')?.value || '0') || 0);
      const baseLayers = Math.max(0, parseInt($('#resinBaseLayers')?.value || '0') || 0);
      const baseExp    = Math.max(0, parseFloat($('#resinBaseExposure')?.value || '0') || 0);
      const layerH     = Math.max(0.01, parseFloat($('#resinLayerHeight')?.value || '0.05') || 0.05);

      const totalSeconds = (layers * exposure) + (baseLayers * baseExp);
      const printTimeHrs = totalSeconds / 3600;

      // Approximate volume: layers × layerHeight(mm) × 40cm² build area = cm³ = mL
      const volMl = layers * layerH * 40;

      const ptEl = $('#printTime');
      if (ptEl) ptEl.value = printTimeHrs.toFixed(2);

      const pwEl = $('#printWeight');
      if (pwEl && !+pwEl.value) pwEl.value = volMl.toFixed(1);  // only fill if empty

      saveBuildDraft();
      toast(t('calc.resin.computed') || `Computed: ${printTimeHrs.toFixed(2)}h · ${volMl.toFixed(1)}mL`, 'success', 3000);
    }
  });

  // Extra materials (Feature 8)
  $('#btnAddExtraMaterial')?.addEventListener('click', () => {
    currentExtraMaterials.push({ material: '', weight: 0 });
    renderExtraMaterials();
  });

  // Feature 5: Add price tier
  $('#btnAddPriceTier')?.addEventListener('click', () => {
    currentPriceTiers.push({ minQty: 1, pricePerUnit: 0 });
    renderPriceTiers();
  });

  // Feature 1 (new batch): Parse G-code / 3MF for print time and weight
  $('#btnParseFile')?.addEventListener('click', async () => {
    if (!window.hubAPI?.pickFile || !window.hubAPI?.parsePrintFile) return;
    const filePath = await window.hubAPI.pickFile({ filters: [{ name: '3D Files', extensions: ['gcode', 'gco', '3mf'] }] });
    if (!filePath) return;
    try {
      const result = await window.hubAPI.parsePrintFile(filePath);
      let filled = false;
      if (result.printTimeMins && result.printTimeMins > 0) {
        const hrs = (result.printTimeMins / 60).toFixed(2);
        const ptEl = $('#printTime');
        if (ptEl) { ptEl.value = hrs; filled = true; }
      }
      if (result.filamentGrams && result.filamentGrams > 0) {
        const pwEl = $('#printWeight');
        if (pwEl) { pwEl.value = result.filamentGrams.toFixed(1); filled = true; }
      }
      if (result.filename) {
        const frEl = $('#partFileRef');
        if (frEl && !frEl.value) frEl.value = result.filename;
      }
      updateGrandTotal();
      if (result.printTimeMins && result.filamentGrams) {
        toast(t('calc.parsed_toast', { time: (result.printTimeMins/60).toFixed(2), grams: result.filamentGrams.toFixed(1) }), 'success');
      } else if (filled) {
        toast(t('calc.parse_partial'), 'info');
      } else {
        toast(t('calc.parse_failed'), 'warning');
      }
    } catch(e) {
      toast(t('calc.parse_failed'), 'warning');
    }
  });

  // Printer presets
  $('#printerPreset').addEventListener('change', (e) => {
    if (e.target.value) applyPreset(e.target.value);
    updateDeletePresetBtn();
  });
  $('#btnSavePreset').addEventListener('click', saveCurrentAsPreset);
  $('#btnDeletePreset').addEventListener('click', deleteCurrentPreset);

  // Job templates
  renderJobTemplateSelect();
  $('#jobTemplateSelect')?.addEventListener('change', e => { if (e.target.value) applyJobTemplate(e.target.value); });
  $('#btnSaveJobTemplate')?.addEventListener('click', saveCurrentAsJobTemplate);
  $('#btnDeleteJobTemplate')?.addEventListener('click', deleteCurrentJobTemplate);

  // Resin exposure profile presets
  renderResinProfiles();
  $('#resinProfileSelect')?.addEventListener('change', e => {
    if (e.target.value) applyResinProfile(e.target.value);
  });
  $('#btnSaveResinProfile')?.addEventListener('click', saveCurrentAsResinProfile);
  $('#btnDeleteResinProfile')?.addEventListener('click', deleteCurrentResinProfile);

  // Quote templates
  $('#quoteTplSelect').addEventListener('change', updateDeleteTplBtn);
  $('#btnLoadTpl').addEventListener('click', loadQuoteTemplate);
  $('#btnSaveTpl').addEventListener('click', saveQuoteTemplate);
  $('#btnDeleteTpl').addEventListener('click', deleteQuoteTemplate);

  // Client autocomplete
  const clientInput = $('#clientInput');
  clientInput.addEventListener('focus', renderClientSuggestions);
  clientInput.addEventListener('input', () => {
    currentClientId = null; // typing implies new/different client
    renderClientSuggestions();
  });
  clientInput.addEventListener('blur', hideClientSuggestions);
  $('#clientSuggestions').addEventListener('mousedown', (e) => {
    e.preventDefault();
    const item = e.target.closest('.suggest-item');
    if (!item) return;
    if (item.dataset.cid) {
      const c = clients.find(x => x.id === item.dataset.cid);
      if (c) {
        const dn = localName(c);
        clientInput.value = dn;
        currentClientId = c.id;
        // Auto-apply client's default discount
        if ((c.defaultDiscount || 0) > 0) {
          const discEl = $('#discountPct');
          if (discEl) { discEl.value = c.defaultDiscount; updateGrandTotal(); }
        }
        // Feature 4: check price list auto-fill
        if ((c.priceList || []).length > 0 && currentBuild.length > 0) {
          let applied = false;
          for (const part of currentBuild) {
            const pl = (c.priceList || []).find(p => p.product && part.name && part.name.toLowerCase().includes(p.product.toLowerCase()));
            if (pl && pl.price > 0) {
              part.unitCost = pl.price;
              part.baseCost = pl.price * (part.qty || 1);
              applied = true;
            }
          }
          if (applied) { renderBuild(); updateGrandTotal(); toast(t('ce.pl_autofill'), 'info', 2000); }
        }
      }
    } else if (item.dataset.act === 'cl-new') {
      // Open client editor with name pre-filled
      const name = item.dataset.name || clientInput.value;
      openClientEditor(null);
      setTimeout(() => {
        const m = $('#modalMount');
        if (m) {
          const ne = m.querySelector('[data-f="nameEn"]');
          if (ne) ne.value = name;
        }
      }, 30);
    }
    $('#clientSuggestions').style.display = 'none';
  });

  // Build cart row clicks
  $('#buildTableBody').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'remove-part') removePart(+btn.dataset.idx);
    if (btn.dataset.act === 'edit-part')   editPart(+btn.dataset.idx);
  });

  // QW4: Calculator autosave — debounced on every field change
  const _calcInputIds = ['#margin','#spoolCost','#spoolWeight','#partQty','#partName','#printWeight','#printTime'];
  let _calcAutosaveTimer = null;
  function _scheduleCalcAutosave() {
    clearTimeout(_calcAutosaveTimer);
    _calcAutosaveTimer = setTimeout(saveBuildDraft, 400);
  }
  _calcInputIds.forEach(sel => {
    $(sel)?.addEventListener('input', _scheduleCalcAutosave);
    $(sel)?.addEventListener('change', _scheduleCalcAutosave);
  });

  // Inventory
  $('#btnAddInv').addEventListener('click', addInventoryItem);
  $('#btnBrowseCatalog').addEventListener('click', openFilamentCatalog);
  // QW7: Dynamic unit label for Resin vs FDM in add form
  $('#invMaterialType')?.addEventListener('change', (e) => {
    const isResin = e.target.value === 'resin';
    const lbl = $('#invWeightUnitSpan');
    if (lbl) lbl.textContent = isResin ? 'mL' : t('common.grams') || 'g';
    const weightLabel = $('#invWeightLabel');
    if (weightLabel) weightLabel.textContent = isResin ? (t('inv.volume_ml') || 'Volume') : (t('inv.weight') || 'Spool weight');
  });
  $('#btnScanLabel').addEventListener('click', openFilamentScanner);
  $('#inventoryTable').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'del-inv')           deleteInventoryItem(btn.dataset.id);
    if (btn.dataset.act === 'edit-inv')          openInventoryEditor(btn.dataset.id);
    if (btn.dataset.act === 'reorder-inv')       openReorderModal(btn.dataset.id);
    if (btn.dataset.act === 'adj-inv')           openStockAdjustModal(btn.dataset.id);
    if (btn.dataset.act === 'inv-spool-history') openSpoolHistory(btn.dataset.id);
    if (btn.dataset.act === 'inv-dry-log')       openDryingLog(btn.dataset.id);
    if (btn.dataset.act === 'inv-test-print')    openTestPrintLog(btn.dataset.id);
    if (btn.dataset.act === 'inv-price-history') openPriceHistory(btn.dataset.id);
    if (btn.dataset.act === 'focus-inv-material') {
      $('#invMaterial')?.focus();
      $('#invMaterial')?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
    }
  });

  document.getElementById('slicerProfilesContainer')?.addEventListener('click', async (e) => {
    const editBtn = e.target.closest('[data-act="edit-slicer-profile"]');
    if (editBtn) { openSlicerProfileModal(editBtn.dataset.id); return; }
    const delBtn = e.target.closest('[data-act="delete-slicer-profile"]');
    if (delBtn) {
      const ok = await confirmModal(t('common.delete') + '?', { danger: true });
      if (ok) deleteSlicerProfile(delBtn.dataset.id);
    }
  });

  $('#modalMount').addEventListener('click', (e) => {
    const milestoneBtn = e.target.closest('[data-act="milestone-invoices"]');
    if (milestoneBtn) openMilestoneInvoices(milestoneBtn.dataset.id);
    const settingsBtn = e.target.closest('[data-act="open-settings-from-modal"]');
    if (settingsBtn) {
      $('#modalMount').innerHTML = '';
      switchTab('settings-tab');
    }
  });

  // Consumables
  $('#btnAddConsumable')?.addEventListener('click', () => openConsumableEditor(null));
  $('#consumablesTable')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'edit-cons') openConsumableEditor(btn.dataset.id);
    if (btn.dataset.act === 'del-cons')  deleteConsumable(btn.dataset.id);
  });

  // Suppliers
  $('#btnAddSupplier')?.addEventListener('click', () => openSupplierEditor(null));
  $('#suppliersTable')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'edit-sup')      openSupplierEditor(btn.dataset.id);
    if (btn.dataset.act === 'del-sup')       deleteSupplier(btn.dataset.id);
    if (btn.dataset.act === 'log-purchase')  openLogPurchaseModal(btn.dataset.id);
    if (btn.dataset.act === 'sup-history')   openSupplierHistory(btn.dataset.id);
    if (btn.dataset.act === 'sup-wa') {
      const sup = suppliers.find(s => s.id === btn.dataset.id);
      if (sup?.phone && window.hubAPI?.shareWhatsApp) {
        window.hubAPI.shareWhatsApp({ phone: sup.phone, message: '', pdfPath: null });
      }
    }
  });

  // Expenses
  $('#btnAddExpense').addEventListener('click', addExpense);
  $('#btnExportExpCsv').addEventListener('click', exportExpensesCsv);
  $('#expRangeFilter').addEventListener('change', (e) => {
    expRangeFilter = e.target.value;
    const cr = $('#expCustomRange');
    if (cr) cr.style.display = expRangeFilter === 'custom' ? 'inline-flex' : 'none';
    renderExpenses();
  });
  $('#expRangeFrom')?.addEventListener('change', (e) => { customRangeFrom.expenses = e.target.value; renderExpenses(); });
  $('#expRangeTo')?.addEventListener('change',   (e) => { customRangeTo.expenses   = e.target.value; renderExpenses(); });
  $('#expenseTable').addEventListener('click', async (e) => {
    const btn = e.target.closest('[data-act="del-exp"]');
    if (btn) { deleteExpense(btn.dataset.id); return; }
    const receiptBtn = e.target.closest('[data-act="open-receipt"]');
    if (receiptBtn && window.hubAPI?.openFile) {
      await window.hubAPI.openFile(receiptBtn.dataset.path);
    }
  });
  // Receipt picker
  const btnExpReceipt = $('#btnExpReceipt');
  if (btnExpReceipt) {
    btnExpReceipt.addEventListener('click', async () => {
      if (!window.hubAPI?.pickFile) return;
      const filePath = await window.hubAPI.pickFile({
        filters: [{ name: 'Images/PDF', extensions: ['jpg','jpeg','png','pdf'] }]
      });
      if (filePath) {
        _expReceiptPath = filePath;
        const nameEl = $('#expReceiptName');
        if (nameEl) {
          const parts = filePath.split('/');
          nameEl.textContent = parts[parts.length - 1];
        }
        toast(t('exp.receipt_attached'), 'success', 2000);
      }
    });
  }
  // Inject locationId select into expense form
  (() => {
    const addBtn = $('#btnAddExpense');
    if (addBtn && !$('#exp_locationId')) {
      const lbl = document.createElement('label');
      lbl.style.marginTop = '12px';
      lbl.textContent = t('mach.location') + ' (' + t('common.optional') + ')';
      const sel = document.createElement('select');
      sel.id = 'exp_locationId';
      const blankOpt = document.createElement('option');
      blankOpt.value = '';
      blankOpt.textContent = '— ' + t('an.unassigned_location') + ' —';
      sel.appendChild(blankOpt);
      locations.forEach(l => {
        const o = document.createElement('option');
        o.value = l.id;
        o.textContent = l.name;
        sel.appendChild(o);
      });
      addBtn.parentNode.insertBefore(sel, addBtn);
      addBtn.parentNode.insertBefore(lbl, sel);
    }
  })();
  // Set default date to today (and enforce max = today)
  const _expTodayStr = new Date().toISOString().split('T')[0];
  $('#expDate').value = _expTodayStr;
  $('#expDate').max   = _expTodayStr;

  // Waste Log
  const btnLogWaste = $('#btnLogWaste');
  if (btnLogWaste) btnLogWaste.addEventListener('click', openWasteForm);
  const wasteTableEl = $('#wasteTable');
  if (wasteTableEl) wasteTableEl.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act="del-waste"]');
    if (btn) deleteWasteEntry(btn.dataset.id);
  });

  // Monthly Tax Summary Export
  const btnTaxExport = $('#btnTaxExport');
  if (btnTaxExport) btnTaxExport.addEventListener('click', exportTaxSummary);

  // Logs — batch bar
  $('#btnBatchPdf').addEventListener('click', batchExportPDFs);
  $('#btnBatchWa').addEventListener('click', batchWaSend);
  $('#btnBatchClear').addEventListener('click', () => { selectedOrders.clear(); renderBatchBar(); renderLogs(); });
  $('#logSelectAll').addEventListener('change', (e) => {
    const checked = e.target.checked;
    const visible = Array.from($('#logTable tbody').querySelectorAll('.log-sel')).map(cb => cb.dataset.id);
    if (checked) visible.forEach(id => selectedOrders.add(id));
    else visible.forEach(id => selectedOrders.delete(id));
    renderBatchBar();
    renderLogs();
  });

  // Logs — row checkbox delegation
  $('#logTable').addEventListener('change', (e) => {
    const cb = e.target.closest('.log-sel');
    if (!cb) return;
    if (cb.checked) selectedOrders.add(cb.dataset.id);
    else selectedOrders.delete(cb.dataset.id);
    renderBatchBar();
    // Re-render just the row highlight without full re-render
    const tr = cb.closest('tr');
    if (tr) tr.style.background = cb.checked ? 'rgba(91,156,240,0.07)' : '';
  });

  // Analytics tab — CSV export buttons
  $('#btnAnOrdersCsv')?.addEventListener('click', exportOrdersCsv);
  $('#btnAnExpensesCsv')?.addEventListener('click', exportExpensesCsv);
  $('#btnExportAnalytics')?.addEventListener('click', exportAnalyticsReport);

  // Logs — search/filter/export
  $('#btnExportCsv').addEventListener('click', exportOrdersCsv);
  $('#btnClearLogs').addEventListener('click', clearAllLogs);
  $('#btnSaveFilterPreset')?.addEventListener('click', saveCurrentFilterPreset);
  $('#btnExportAccounting')?.addEventListener('click', exportAccountingCSV);
  let _logSearchTimer = null;
  $('#logSearch').addEventListener('input', (e) => {
    logSearchTerm = e.target.value;
    clearTimeout(_logSearchTimer);
    _logSearchTimer = setTimeout(renderLogs, 150);
  });
  $('#logStatusFilter').addEventListener('change', (e) => { logStatusFilter = e.target.value; renderLogs(); });
  $('#logPayFilter').addEventListener('change', (e) => { logPayFilter = e.target.value; renderLogs(); });
  $('#logRangeFilter').addEventListener('change', (e) => {
    logRangeFilter = e.target.value;
    const cr = $('#logCustomRange');
    if (cr) cr.style.display = logRangeFilter === 'custom' ? 'inline-flex' : 'none';
    renderLogs();
  });
  $('#logRangeFrom')?.addEventListener('change', (e) => { customRangeFrom.log = e.target.value; renderLogs(); });
  $('#logRangeTo')?.addEventListener('change',   (e) => { customRangeTo.log   = e.target.value; renderLogs(); });
  $('#logTagFilter')?.addEventListener('change', (e) => { logTagFilter = e.target.value; renderLogs(); });
  $('#logClientFilter')?.addEventListener('change', (e) => { logClientFilter = e.target.value; renderLogs(); });
  // QW1: Sortable log table headers
  $('#logTable thead').addEventListener('click', (e) => {
    const th = e.target.closest('th[data-sort]');
    if (!th) return;
    const col = th.dataset.sort;
    if (logSortCol === col) {
      logSortDir = logSortDir === 'asc' ? 'desc' : 'asc';
    } else {
      logSortCol = col;
      logSortDir = col === 'date' ? 'desc' : 'asc';
    }
    renderLogs();
  });
  // QW6: Operator filter
  $('#logOperatorFilter')?.addEventListener('change', (e) => { logOperatorFilter = e.target.value; renderLogs(); });
  $('#logTable').addEventListener('click', (e) => {
    const clearFiltersBtn = e.target.closest('[data-act="clear-log-filters"]');
    if (clearFiltersBtn) { clearLogFilters(); return; }
    const newOrdBtn = e.target.closest('[data-act="new-order"]');
    if (newOrdBtn) { logPrint(); return; }
    const loadMoreBtn = e.target.closest('[data-act="load-more-logs"]');
    if (loadMoreBtn) { logDisplayLimit += 100; renderLogs(); return; }
    const bnplPay = e.target.closest('[data-act="bnpl-pay"]');
    if (bnplPay) { openBnplModal(bnplPay.dataset.id); return; }
    const inv  = e.target.closest('[data-act="invoice"]');
    const pdf  = e.target.closest('[data-act="inv-pdf"]');
    const wa   = e.target.closest('[data-act="inv-wa"]');
    const dn   = e.target.closest('[data-act="dn-log"]');
    const cn   = e.target.closest('[data-act="cn-log"]');
    const voidInv = e.target.closest('[data-act="void-invoice"]');
    const wo   = e.target.closest('[data-act="wo-log"]');
    const pay  = e.target.closest('[data-act="pay"]');
    const unp  = e.target.closest('[data-act="unpay"]');
    const timeline = e.target.closest('[data-act="order-timeline"]');
    if (timeline) { openOrderTimeline(timeline.dataset.id); return; }
    const edit    = e.target.closest('[data-act="edit-log"]');
    const dup     = e.target.closest('[data-act="dup-log"]');
    const reprint = e.target.closest('[data-act="reprint-log"]');
    const del     = e.target.closest('[data-act="del-log"]');
    const tagBtn = e.target.closest('[data-act="filter-tag"]');
    if (inv)     generateInvoice(inv.dataset.id);
    if (pdf)     exportInvoicePDF(pdf.dataset.id, { askWhere: true, openAfter: true });
    if (wa)      shareInvoiceWhatsApp(wa.dataset.id);
    if (dn)      generateDeliveryNote(dn.dataset.id);
    if (cn)      openCreditNoteModal(cn.dataset.id);
    if (voidInv) voidInvoice(voidInv.dataset.id);
    if (wo)      generateWorkOrder(wo.dataset.id);
    const remind = e.target.closest('[data-act="pay-remind"]');
    if (remind)  sendPaymentReminder(remind.dataset.id);
    const tracking = e.target.closest('[data-act="share-tracking"]');
    if (tracking) shareTrackingWhatsApp(tracking.dataset.id);
    if (pay)     openPaymentModal(pay.dataset.id);
    if (unp)     clearPayment(unp.dataset.id);
    if (edit)    openOrderEditor(edit.dataset.id);
    if (dup)     duplicateOrder(dup.dataset.id);
    if (reprint) reprintOrder(reprint.dataset.id);
    const labelBtn2 = e.target.closest('[data-act="print-label"]');
    if (labelBtn2) { generateOrderLabel(labelBtn2.dataset.id); return; }
    const packSlipBtn = e.target.closest('[data-act="packing-slip"]');
    if (packSlipBtn) { generatePackingSlip(packSlipBtn.dataset.id); return; }
    if (del)     deleteLog(del.dataset.id);
    const linkedExp = e.target.closest('[data-act="linked-expenses"]');
    if (linkedExp) showLinkedExpenses(linkedExp.dataset.id);
    const emailInv = e.target.closest('[data-act="email-invoice"]');
    if (emailInv) emailOrderToClient(emailInv.dataset.id, false);
    const emailQuo = e.target.closest('[data-act="email-quote"]');
    if (emailQuo) emailOrderToClient(emailQuo.dataset.id, true);
    const zatcaSubmitBtn = e.target.closest('[data-act="zatca-submit"]');
    if (zatcaSubmitBtn) {
      submitOrderToZatca(zatcaSubmitBtn.dataset.id, { manual: true });
      return;
    }
    const statusPage = e.target.closest('[data-act="export-status-page"]');
    if (statusPage) exportOrderStatusPage(statusPage.dataset.id);
    const portalQrBtn = e.target.closest('[data-act="portal-qr"]');
    if (portalQrBtn) { openCustomerPortalModal(portalQrBtn.dataset.id); return; }
    const quoteLinkBtn = e.target.closest('[data-act="quote-approval-link"]');
    if (quoteLinkBtn) { openQuoteApprovalLinkModal(quoteLinkBtn.dataset.id); return; }
    const logTimeBtn = e.target.closest('[data-act="log-time"]');
    if (logTimeBtn) { openTimeEntryModal(logTimeBtn.dataset.id); return; }
    const openStatusPage = e.target.closest('[data-act="open-status-page"]');
    if (openStatusPage) openSavedStatusPage(openStatusPage.dataset.id);
    const copyUrlBtn = e.target.closest('[data-act="copy-tracking-url"]');
    if (copyUrlBtn) {
      (async () => {
        const lanInfo = await window.hubAPI?.getLanUrl?.();
        if (!lanInfo?.ok) {
          toast(t('ord.tracking_no_lan') || 'LAN server is not running — enable it in Settings', 'warning', 4000);
          return;
        }
        const ord = printLog.find(o => o.id === copyUrlBtn.dataset.id);
        const url = ord ? buildLanOrderTrackingUrl(lanInfo.url, ord) : '';
        if (!url) {
          toast(t('ord.tracking_no_lan') || 'LAN server is not running — enable it in Settings', 'warning', 4000);
          return;
        }
        try {
          await navigator.clipboard.writeText(url);
          toast(t('ord.tracking_copied') || 'Tracking URL copied', 'success', 4000);
        } catch {
          toast(url, 'info', 8000);
        }
      })();
      return;
    }
    const splitOrderBtn = e.target.closest('[data-act="split-order"]');
    if (splitOrderBtn) splitOrderAcrossMachines(splitOrderBtn.dataset.id);
    const editHistBtn = e.target.closest('[data-act="view-edit-history"]');
    if (editHistBtn) openEditHistoryModal(editHistBtn.dataset.id);
    const quoteApproval = e.target.closest('[data-act="export-quote-approval"]');
    if (quoteApproval) exportQuoteApprovalPage(quoteApproval.dataset.id);
    const reviseQuoteBtn = e.target.closest('[data-act="revise-quote"]');
    if (reviseQuoteBtn) reviseQuote(reviseQuoteBtn.dataset.id);
    const quoteRevisionsBtn = e.target.closest('[data-act="quote-revisions"]');
    if (quoteRevisionsBtn) openQuoteRevisionsModal(quoteRevisionsBtn.dataset.id);
    const partialDeliveryBtn = e.target.closest('[data-act="partial-delivery"]');
    if (partialDeliveryBtn) openPartialDeliveryModal(partialDeliveryBtn.dataset.id);
    const spoolSwitchBtn = e.target.closest('[data-act="log-spool-switch"]');
    if (spoolSwitchBtn) openSpoolSwitchModal(spoolSwitchBtn.dataset.id);
    const archBtn  = e.target.closest('[data-act="archive-log"]');
    const unarchBtn = e.target.closest('[data-act="unarchive-log"]');
    if (archBtn) {
      const o = printLog.find(x => x.id === archBtn.dataset.id);
      if (o) { o.archived = true; saveAll(); renderLogs(); toast(t('ord.archived') || 'Order archived', 'success'); }
      return;
    }
    if (unarchBtn) {
      const o = printLog.find(x => x.id === unarchBtn.dataset.id);
      if (o) { delete o.archived; saveAll(); renderLogs(); toast(t('ord.unarchived') || 'Order restored', 'success'); }
      return;
    }
    // New Feature 3: Proforma invoice
    const proformaBtn = e.target.closest('[data-act="gen-proforma"]');
    if (proformaBtn) generateProformaInvoice(proformaBtn.dataset.id);
    // Milestone invoices
    const milestoneBtn = e.target.closest('[data-act="milestone-invoices"]');
    if (milestoneBtn) openMilestoneInvoices(milestoneBtn.dataset.id);
    // Round 12: NPS survey actions
    const surveyBtn = e.target.closest('[data-act="gen-survey"]');
    if (surveyBtn) generateSurveyPage(surveyBtn.dataset.id);
    const recordSurveyBtn = e.target.closest('[data-act="record-survey"]');
    if (recordSurveyBtn) openRecordSurveyModal(recordSurveyBtn.dataset.id);
    // Batch-2 Feature 13: Change Order from logs table
    const changeOrderLogBtn = e.target.closest('[data-act="change-order"]');
    if (changeOrderLogBtn) { openChangeOrderModal(changeOrderLogBtn.dataset.id); return; }
    if (tagBtn) {
      logTagFilter = tagBtn.dataset.tag;
      const sel = $('#logTagFilter');
      if (sel) sel.value = logTagFilter;
      renderLogs();
    }
  });

  // Portfolio
  $('#portfolioSearch').addEventListener('input', (e) => { portfolioSearchTerm = e.target.value; renderPortfolio(); });
  $('#portfolioGrid').addEventListener('click', (e) => {
    const cell = e.target.closest('.portfolio-cell');
    if (cell) openOrderEditor(cell.dataset.oid);
  });
  $('#btnRevealOrderPhotos').addEventListener('click', () => {
    if (window.hubAPI?.revealOrderPhotosFolder) window.hubAPI.revealOrderPhotosFolder();
  });

  // Kanban — production columns
  document.querySelector('.kanban').addEventListener('click', (e) => {
    const kanbanTimeline = e.target.closest('[data-act="order-timeline"]');
    if (kanbanTimeline) { openOrderTimeline(kanbanTimeline.dataset.id); return; }
    const logWasteCard = e.target.closest('[data-act="log-waste-card"]');
    if (logWasteCard) { openLogWasteFromCard(logWasteCard.dataset.id); return; }
    const bnplPay = e.target.closest('[data-act="bnpl-pay"]');
    if (bnplPay) { openBnplModal(bnplPay.dataset.id); return; }
    const s  = e.target.closest('[data-act="status"]');
    const i  = e.target.closest('[data-act="invoice"]');
    const wa = e.target.closest('[data-act="wa-quick"]');
    const md = e.target.closest('[data-act="mark-delivered"]');
    const wo = e.target.closest('[data-act="wo-kanban"]');
    const qUp = e.target.closest('[data-act="q-up"]');
    const qDn = e.target.closest('[data-act="q-down"]');
    const tps = e.target.closest('[data-act="toggle-part-status"]');
    const holdBtn = e.target.closest('[data-act="hold-order"]');
    const qcPassBtn = e.target.closest('[data-act="qc-pass"]');
    const qcFailBtn = e.target.closest('[data-act="qc-fail"]');
    const resumeBtn = e.target.closest('[data-act="resume-production"]');
    const resinWashBtn = e.target.closest('[data-act="resin-log-wash"]');
    const resinCureBtn = e.target.closest('[data-act="resin-log-cure"]');
    const resinCompleteBtn = e.target.closest('[data-act="resin-complete"]');
    const shareTrackBtn = e.target.closest('[data-act="share-tracking-link"]');
    const printLabelBtn = e.target.closest('[data-act="print-label"]');
    const pauseTimerBtn = e.target.closest('[data-act="pause-timer"]');
    const resumeTimerBtn = e.target.closest('[data-act="resume-timer"]');
    if (s)  updateStatus(s.dataset.id, s.dataset.to);
    if (printLabelBtn) { generateOrderLabel(printLabelBtn.dataset.id); return; }
    if (pauseTimerBtn) {
      const ord = printLog.find(o => o.id === pauseTimerBtn.dataset.id);
      if (ord && ord.timerStart && !ord.timerPausedAt) {
        ord.timerPausedAt = new Date().toISOString();
        saveAll(); renderKanban();
      }
      return;
    }
    if (resumeTimerBtn) {
      const ord = printLog.find(o => o.id === resumeTimerBtn.dataset.id);
      if (ord && ord.timerPausedAt) {
        ord.timerPausedMs = (ord.timerPausedMs || 0) + (Date.now() - new Date(ord.timerPausedAt).getTime());
        delete ord.timerPausedAt;
        saveAll(); renderKanban();
      }
      return;
    }
    if (holdBtn) holdOrder(holdBtn.dataset.id);
    if (qcPassBtn) qcPassOrder(qcPassBtn.dataset.id);
    if (qcFailBtn) qcFailOrder(qcFailBtn.dataset.id);
    if (resumeBtn) resumeProduction();
    if (resinWashBtn) resinLogWash(resinWashBtn.dataset.id);
    if (resinCureBtn) resinLogCure(resinCureBtn.dataset.id);
    if (resinCompleteBtn) resinCompletePost(resinCompleteBtn.dataset.id);
    if (i)  generateInvoice(i.dataset.id);
    if (wa) openWaSendModal(wa.dataset.id);
    if (md) markDelivered(md.dataset.id);
    if (wo) generateWorkOrder(wo.dataset.id);
    if (shareTrackBtn) {
      const ordId = shareTrackBtn.dataset.id;
      exportOrderStatusPage(ordId)
        .then(() => {
          const path = `userData/status-pages/order-status-${ordId}.html`;
          toast(`📄 ${escapeHtml(t('ord.status_page_saved') || 'Tracking page saved')} · ${path}`, 'success', 5000);
        })
        .catch((e) => {
          console.error('exportOrderStatusPage:', e);
          toast(t('ord.status_page_error') || 'Could not save tracking page', 'error');
        });
    }
    if (tps) {
      const order = printLog.find(o => o.id === tps.dataset.orderId);
      const partIdx = parseInt(tps.dataset.partIndex, 10);
      if (order && order.parts && order.parts[partIdx] !== undefined) {
        const cycle = ['pending', 'printing', 'done', 'failed'];
        const cur = order.parts[partIdx].partStatus || 'pending';
        const next = cycle[(cycle.indexOf(cur) + 1) % cycle.length];
        order.parts[partIdx].partStatus = next;
        saveAll();
        renderKanban();
      }
    }
    if (qUp) {
      // Swap queuePos with the previous pending order
      const pending = printLog.filter(o => o.status === 'pending')
        .sort((a, b) => (a.queuePos || 9999) - (b.queuePos || 9999));
      const idx = pending.findIndex(o => o.id === qUp.dataset.id);
      if (idx > 0) {
        const t1 = pending[idx].queuePos; pending[idx].queuePos = pending[idx - 1].queuePos; pending[idx - 1].queuePos = t1;
        saveAll(); renderKanban();
      }
    }
    if (qDn) {
      const pending = printLog.filter(o => o.status === 'pending')
        .sort((a, b) => (a.queuePos || 9999) - (b.queuePos || 9999));
      const idx = pending.findIndex(o => o.id === qDn.dataset.id);
      if (idx >= 0 && idx < pending.length - 1) {
        const t2 = pending[idx].queuePos; pending[idx].queuePos = pending[idx + 1].queuePos; pending[idx + 1].queuePos = t2;
        saveAll(); renderKanban();
      }
    }
    // Batch-2 Feature 13: Change Order
    const changeOrderBtn = e.target.closest('[data-act="change-order"]');
    if (changeOrderBtn) { openChangeOrderModal(changeOrderBtn.dataset.id); return; }
    // Batch-2 Feature 14: Failure photo capture
    const failPhotoBtn = e.target.closest('[data-act="capture-failure-photo"]');
    if (failPhotoBtn) { captureFailurePhoto(failPhotoBtn.dataset.id); return; }
  });

  // Post-checklist checkbox changes (delegated from kanban, uses change not click)
  document.querySelector('.kanban').addEventListener('change', (e) => {
    const cb = e.target.closest('.post-check-cb');
    if (!cb) return;
    const order = printLog.find(o => o.id === cb.dataset.order);
    if (!order) return;
    if (!order.postChecks) order.postChecks = {};
    order.postChecks[cb.dataset.check] = cb.checked;
    saveAll();
    // Update the card header count without full re-render
    const card = cb.closest('.post-checklist');
    if (card) {
      const header = card.querySelector('.post-check-count');
      if (header) {
        const total = card.querySelectorAll('.post-check-cb').length;
        const done  = card.querySelectorAll('.post-check-cb:checked').length;
        header.textContent = `${done}/${total}`;
      }
      // Toggle done class on label
      const label = cb.closest('.post-check-item');
      if (label) label.classList.toggle('done', cb.checked);
    }
  });

  // Kanban — quotes section
  $('#quotesSection').addEventListener('click', (e) => {
    const approve = e.target.closest('[data-act="approve-quote"]');
    const reject  = e.target.closest('[data-act="reject-quote"]');
    const share   = e.target.closest('[data-act="share-quote"]');
    const quoteLink = e.target.closest('[data-act="quote-approval-link"]');
    if (approve) approveQuote(approve.dataset.id);
    if (reject)  rejectQuote(reject.dataset.id);
    if (share)   exportInvoicePDF(share.dataset.id, { askWhere: true, openAfter: true });
    if (quoteLink) openQuoteApprovalLinkModal(quoteLink.dataset.id);
  });

  // Save-as-Quote button
  $('#btnSaveAsQuote').addEventListener('click', () => logPrint(true));

  // Production pause button
  $('#btnPauseProduction')?.addEventListener('click', pauseProduction);

  // Kanban search filter
  let _kanSearchTimer = null;
  $('#kanSearch')?.addEventListener('input', (e) => {
    kanSearchTerm = e.target.value;
    clearTimeout(_kanSearchTimer);
    _kanSearchTimer = setTimeout(renderKanban, 150);
  });

  // Schedule view toggle (Feature 2)
  $('#btnScheduleView')?.addEventListener('click', () => {
    const sv = $('#scheduleView');
    const kanban = document.querySelector('.kanban');
    if (!sv || !kanban) return;
    const isVisible = sv.style.display !== 'none';
    if (isVisible) {
      sv.style.display = 'none';
      kanban.style.display = '';
      $('#btnScheduleView').innerHTML = `📅 <span data-i18n="kan.schedule_view">${t('kan.schedule_view')}</span>`;
    } else {
      sv.style.display = '';
      kanban.style.display = 'none';
      renderScheduleView();
      $('#btnScheduleView').innerHTML = `📋 <span data-i18n="kan.kanban_view">${t('kan.kanban_view')}</span>`;
      // Close calendar/kiosk views if open
      const cv = $('#calendarView');
      if (cv) cv.style.display = 'none';
      const kv = $('#kioskView');
      if (kv) kv.style.display = 'none';
    }
  });

  $('#btnBatchPlanner')?.addEventListener('click', openBatchPlannerModal);

  // Kiosk view toggle
  $('#btnKioskView')?.addEventListener('click', () => {
    const el = $('#kioskView');
    if (!el) return;
    const isVisible = el.style.display !== 'none';
    el.style.display = isVisible ? 'none' : 'block';
    if (!isVisible) renderKioskView();
    // Close other views
    const sv = $('#scheduleView');
    const cv = $('#calendarView');
    if (sv && el.style.display !== 'none') sv.style.display = 'none';
    if (cv && el.style.display !== 'none') cv.style.display = 'none';
  });

  // Kanban priority sort toggle
  $('#btnKanbanSort')?.addEventListener('click', () => {
    kanbanSortByPriority = !kanbanSortByPriority;
    const btn = $('#btnKanbanSort');
    if (btn) {
      btn.style.background = kanbanSortByPriority ? 'rgba(99,102,241,0.2)' : '';
      btn.style.color = kanbanSortByPriority ? '#818cf8' : '';
      btn.style.borderColor = kanbanSortByPriority ? 'rgba(99,102,241,0.5)' : '';
    }
    renderKanban();
    toast(kanbanSortByPriority ? t('queue.sort_on') : t('queue.sort_off'), 'info');
  });

  // Batch-2 Feature 2: Shift checklist
  $('#btnStartShift')?.addEventListener('click', openShiftChecklistModal);
  // Batch-2 Feature 3: End of day report
  $('#btnEndOfDay')?.addEventListener('click', openEndOfDayReport);
  // Batch-2 Feature 11: iCal export
  $('#btnExportIcal')?.addEventListener('click', exportIcalFeed);
  // Batch-2 Feature 5: Gift cards
  $('#btnCreateGiftCard')?.addEventListener('click', openCreateGiftCardModal);
  // Batch-2 Feature 8: Slicer profiles
  $('#btnAddSlicerProfile')?.addEventListener('click', () => openSlicerProfileModal(null));
  // Batch-2 Feature 9: Env log
  $('#btnLogEnv')?.addEventListener('click', openLogEnvModal);
  // Batch-2 Feature 7: VAT return export
  $('#btnExportVatReturn')?.addEventListener('click', () => {
    const periodSel = $('#vatReturnPeriod');
    exportGaztVatReturn(periodSel ? periodSel.value : 'year');
  });

  // Waiting list
  $('#btnAddWaiting')?.addEventListener('click', () => openWaitingItemEditor(null));
  $('#waitingListToggle')?.addEventListener('click', () => {
    if (window.KhaytStudio?.isStudio?.()) return;
    const section = $('#waitingListSection');
    const chevron = $('#waitingChevron');
    const toggle = $('#waitingListToggle');
    if (!section) return;
    const hidden = section.style.display === 'none';
    section.style.display = hidden ? 'block' : 'none';
    if (chevron) chevron.textContent = hidden ? '▲' : '▼';
    if (toggle) toggle.setAttribute('aria-expanded', hidden ? 'true' : 'false');
  });
  $('#waitingListSection')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    const id = btn.dataset.id;
    if (btn.dataset.act === 'waiting-edit') openWaitingItemEditor(id);
    if (btn.dataset.act === 'waiting-remind') { openReminderModal(id); return; }
    if (btn.dataset.act === 'waiting-decline') {
      const item = waitingList.find(w => w.id === id);
      if (item) {
        waitingListHistory.push({ ...item, status: 'declined', declinedAt: new Date().toISOString() });
        waitingList = waitingList.filter(w => w.id !== id);
        saveAll(); renderWaitingList(); updateWaitingBadge();
      }
      return;
    }
    if (btn.dataset.act === 'waiting-del') {
      waitingList = waitingList.filter(w => w.id !== id);
      saveAll();
      renderWaitingList();
      updateWaitingBadge();
    }
    if (btn.dataset.act === 'waiting-promote') promoteWaitingItem(id);
  });

  // Calendar view toggle
  $('#btnCalendarView')?.addEventListener('click', () => {
    const el = $('#calendarView');
    if (!el) return;
    const isVisible = el.style.display !== 'none';
    el.style.display = isVisible ? 'none' : 'block';
    if (!isVisible) {
      calendarViewMonth = null;
      renderCalendarView();
    }
    // If schedule view is open, close it
    const sv = $('#scheduleView');
    if (sv && el.style.display !== 'none') sv.style.display = 'none';
  });

  // Machine profiles (settings section)
  $('#btnAddMachine').addEventListener('click', () => openMachineEditor(null));
  $('#machinesList').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'maint-log') openMaintLog(btn.dataset.id);
    if (btn.dataset.act === 'edit-mach') openMachineEditor(btn.dataset.id);
    if (btn.dataset.act === 'del-mach') deleteMachine(btn.dataset.id);
    if (btn.dataset.act === 'log-nozzle-change') logNozzleChange(btn.dataset.id);
  });

  // Feature 8 (new): Locations settings
  $('#btnAddLocation')?.addEventListener('click', () => openLocationEditor(null));
  $('#locationsSettingsSection')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'edit-loc') openLocationEditor(btn.dataset.id);
    if (btn.dataset.act === 'del-loc') {
      locations = locations.filter(l => l.id !== btn.dataset.id);
      saveAll();
      renderLocationsSettings();
      renderLocationFilter();
    }
  });

  // Feature 8 (new): Location filter
  $('#locationFilter')?.addEventListener('change', (e) => {
    activeLocation = e.target.value || null;
    renderDashboard();
    renderAnalytics();
    renderKanban();
    renderLogs();
    renderInventory();
  });

  // Operators management (settings section, Feature 1)
  $('#btnAddOperator')?.addEventListener('click', () => openOperatorEditor(null));
  $('#operatorsList')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'edit-operator') openOperatorEditor(btn.dataset.id);
    if (btn.dataset.act === 'del-operator') {
      operators = operators.filter(o => o.id !== btn.dataset.id);
      saveAll();
      renderOperatorsList();
    }
  });

  // WA template management (settings section)
  $('#btnAddWaTemplate').addEventListener('click', () => openWaTemplateEditor(null));
  $('#waTemplatesList').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'edit-wa-tpl') openWaTemplateEditor(btn.dataset.id);
    if (btn.dataset.act === 'del-wa-tpl') deleteWaTemplate(btn.dataset.id);
  });

  // Analytics range
  $('#analyticsRange').addEventListener('change', (e) => {
    analyticsRange = e.target.value;
    const cr = $('#analyticsCustomRange');
    if (cr) cr.style.display = analyticsRange === 'custom' ? 'inline-flex' : 'none';
    renderAnalytics();
  });
  $('#analyticsRangeFrom')?.addEventListener('change', (e) => { customRangeFrom.analytics = e.target.value; renderAnalytics(); });
  $('#analyticsRangeTo')?.addEventListener('change',   (e) => { customRangeTo.analytics   = e.target.value; renderAnalytics(); });

  // Catalog
  $('#btnImportProductsCsv')?.addEventListener('click', importProductsCsv);
  $('#btnAddProduct').addEventListener('click', () => openProductEditor(null));
  $('#catalogSearch').addEventListener('input', (e) => { catalogSearchTerm = e.target.value; renderCatalog(); });
  $('#invSearch')?.addEventListener('input', (e) => { invSearchTerm = e.target.value; renderInventory(); });
  $('#supplierSearch')?.addEventListener('input', (e) => { supplierSearchTerm = e.target.value; renderSuppliers(); });
  // QW9: Waste log filters
  $('#wasteSearch')?.addEventListener('input', (e) => { wasteSearchTerm = e.target.value; renderWasteLog(); });
  $('#wasteMaterialFilter')?.addEventListener('change', (e) => { wasteMaterialFilter = e.target.value; renderWasteLog(); });
  $('#wasteFailureFilter')?.addEventListener('change', (e) => { wasteFailureFilter = e.target.value; renderWasteLog(); });
  $('#wasteDateFilter')?.addEventListener('change', (e) => { wasteDateFilter = e.target.value; renderWasteLog(); });
  $('#catalogGrid').addEventListener('click', (e) => {
    const quote = e.target.closest('[data-act="cat-quote"]');
    const edit  = e.target.closest('[data-act="cat-edit"]');
    const del   = e.target.closest('[data-act="cat-del"]');
    if (quote) quoteFromProduct(quote.dataset.id);
    if (edit)  openProductEditor(edit.dataset.id);
    if (del)   deleteProduct(del.dataset.id);
  });

  // Dashboard click delegation (recurring order start, order edit, payment reminder)
  $('#dashboardContent')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'cl-quote')   quoteForClient(btn.dataset.id);
    if (btn.dataset.act === 'edit-log')   openOrderEditor(btn.dataset.id);
    if (btn.dataset.act === 'pay-remind') sendPaymentReminder(btn.dataset.id);
    if (btn.dataset.act === 'log-service') logMachineService(btn.dataset.id);
    if (btn.dataset.act === 'remind-instalment') {
      const order = printLog.find(o => o.id === btn.dataset.orderId);
      if (!order) return;
      const instIdx = parseInt(btn.dataset.instIndex, 10);
      const inst = (order.instalments || [])[instIdx];
      if (!inst) return;
      const client = order.clientId ? clients.find(c => c.id === order.clientId) : null;
      const clientName = client ? localName(client) : (order.project || order.id);
      const msg = `Hi ${clientName}! A payment of ${fmtMoney(inst.amount || 0)} ${currencySymbol()} for order #${order.id} (${inst.note || ''}) is due on ${inst.dueDate || ''}. Please let us know if you have any questions.`;
      const phone = client?.phone || '';
      if (window.hubAPI?.shareWhatsApp) {
        window.hubAPI.shareWhatsApp({ phone, message: msg, pdfPath: null });
      }
    }
  });

  // Clients
  $('#btnImportSpoolsCsv')?.addEventListener('click', importSpoolsCsv);
  $('#btnImportClientsCsv')?.addEventListener('click', importClientsCsv);
  $('#btnExportClientsCsv')?.addEventListener('click', () => exportClientsCsv());
  $('#btnExportInventoryCsv')?.addEventListener('click', () => exportInventoryCsv());
  $('#btnAddClient').addEventListener('click', () => openClientEditor(null));
  $('#btnBlankIntakeForm')?.addEventListener('click', () => generateIntakeForm(null));
  $('#clientSearch').addEventListener('input', (e) => { clientSearchTerm = e.target.value; renderClients(); });
  $('#clientsTable').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act]');
    if (!btn) return;
    if (btn.dataset.act === 'cl-history')     openClientHistory(btn.dataset.id);
    if (btn.dataset.act === 'cl-quote')       quoteForClient(btn.dataset.id);
    if (btn.dataset.act === 'cl-intake-form') generateIntakeForm(btn.dataset.id);
    if (btn.dataset.act === 'cl-note') {
      const id = btn.dataset.id;
      const client = clients.find(c => c.id === id);
      if (!client) return;
      const channels = ['email','phone','whatsapp','in-person','other'];
      openFormModal({
        title: `💬 ${t('cl.add_note')} — ${escapeHtml(localName(client) || client.id)}`,
        saveLabel: t('common.save'),
        bodyHtml: `
          <label>${escapeHtml(t('cl.comm_channel'))}</label>
          <select id="clNoteChannel">
            ${channels.map(ch => `<option value="${ch}">${escapeHtml(ch)}</option>`).join('')}
          </select>
          <label style="margin-top:12px;">${escapeHtml(t('cl.comm_note'))}</label>
          <textarea id="clNoteText" rows="4" placeholder="${escapeHtml(t('cl.comm_note_ph'))}"></textarea>`,
        onSave() {
          const channel = $('#clNoteChannel')?.value || 'other';
          const note    = ($('#clNoteText')?.value || '').trim();
          if (!note) { toast(t('cl.comm_note_required') || 'Note is required', 'error'); return false; }
          const entry = { channel, note, at: new Date().toISOString(), quick: true };
          if (!client.commLog) client.commLog = [];
          client.commLog.unshift(entry);
          if (client.commLog.length > 200) client.commLog.length = 200;
          saveAll();
          renderClients();
          toast(`💬 ${t('cl.note_saved') || 'Note saved'}`, 'success');
          return true;
        }
      });
    }
    if (btn.dataset.act === 'cl-edit')        openClientEditor(btn.dataset.id);
    if (btn.dataset.act === 'cl-del')         deleteClient(btn.dataset.id);
  });

  // Post-processing checklist settings
  $('#btnAddPostCheck')?.addEventListener('click', addPostCheckItem);
  $('#postCheckInput')?.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); addPostCheckItem(); } });
  $('#postChecklistItems')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act="del-post-check"]');
    if (btn) deletePostCheckItem(+btn.dataset.idx);
  });

  // Custom order fields
  $('#btnAddCustomField')?.addEventListener('click', addCustomField);

  // New Feature 7: Working hours — holiday add/remove
  $('#btnAddHoliday')?.addEventListener('click', () => {
    const inp = $('#set_holidayInput');
    const d = inp?.value;
    if (!d) return;
    if (!settings.holidays) settings.holidays = [];
    if (!settings.holidays.includes(d)) {
      settings.holidays.push(d);
      renderHolidayList();
    }
    if (inp) inp.value = '';
  });
  $('#holidayList')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act="rm-holiday"]');
    if (!btn) return;
    settings.holidays = (settings.holidays || []).filter(x => x !== btn.dataset.date);
    renderHolidayList();
    toast(t('set.holiday_removed'), 'info', 2000);
  });
  $('#customFieldInput')?.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); addCustomField(); } });
  $('#customFieldsList')?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-act="del-custom-field"]');
    if (btn) deleteCustomField(+btn.dataset.idx);
  });

  // Operational settings save — delegate to saveSettingsFromForm so all fields are preserved
  $('#btnSaveOpsSettings')?.addEventListener('click', () => {
    saveSettingsFromForm();
    renderExpenses();
  });

  // Settings
  $('#btnSaveSettings')?.addEventListener('click', saveSettingsFromForm);

  // Settings panel Save buttons (Preferences, Stock, Invoice, Online, etc.)
  document.addEventListener('click', (e) => {
    const savePanel = e.target.closest('[data-act="save-settings-from-panel"]');
    if (savePanel) {
      (typeof saveSettingsFromPanel === 'function' ? saveSettingsFromPanel : saveSettingsFromForm)();
      return;
    }
  });

  // Settings sidebar navigation
  document.addEventListener('click', e => {
    const navItem = e.target.closest('.settings-nav-item[data-settings-section]');
    if (!navItem) return;
    const open = typeof openSettingsSection === 'function'
      ? openSettingsSection
      : global.KhaytShell?.openSettingsSection;
    if (open) open(navItem.dataset.settingsSection);
  });

  // Business Mode toggle buttons (in Settings tab)
  $$('#btnModeSimple, #btnModePro').forEach(btn => {
    btn?.addEventListener('click', () => {
      settings.mode = btn.dataset.mode;
      saveAll();
      applyMode();
      toast(t('set.mode_changed'), 'success');
      // Re-render analytics tab if it's currently active
      applyAnalyticsModeView();
    });
  });
  $('#logoUploadInput').addEventListener('change', (e) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    if (file.size > 1024 * 1024) { toast(t('set.logo_too_big'), 'error'); return; }
    const reader = new FileReader();
    reader.onload = (ev) => {
      const result = ev.target.result;
      if (!result.startsWith('data:image/')) {
        toast(t('settings.logo_invalid_type') || 'Logo must be an image file', 'error');
        return;
      }
      settings.bizLogo = result;
      saveAll();
      updateLogoPreview();
      toast(t('set.logo_saved'), 'success');
    };
    reader.readAsDataURL(file);
  });
  $('#btnRemoveLogo').addEventListener('click', () => {
    settings.bizLogo = '';
    saveAll();
    updateLogoPreview();
    toast(t('set.logo_removed'), 'success');
  });
  $('#btnExport').addEventListener('click', exportData);
  $('#btnImport').addEventListener('click', () => $('#importFile').click());
  $('#importFile').addEventListener('change', (e) => {
    if (e.target.files[0]) importData(e.target.files[0]);
    e.target.value = '';
  });
  $('#btnReset').addEventListener('click', resetAllData);
  $('#btnFullWipe').addEventListener('click', fullWipeData);
  $('#btnRevealPhotos').addEventListener('click', () => {
    if (window.hubAPI?.revealProductsFolder) window.hubAPI.revealProductsFolder();
  });
  $('#btnRevealBackups').addEventListener('click', () => {
    if (window.hubAPI?.revealBackupsFolder) window.hubAPI.revealBackupsFolder();
  });
  $('#btnRestoreBackup')?.addEventListener('click', openRestoreBackupModal);

  // Purchase orders (Feature 3) — delegate from section
  $('#poSection')?.addEventListener('click', async (e) => {
    const loadMorePos = e.target.closest('[data-act="load-more-pos"]');
    if (loadMorePos) { poDisplayLimit += 50; renderPurchaseOrders(); return; }
    const recv    = e.target.closest('[data-act="po-receive"]');
    const del     = e.target.closest('[data-act="po-del"]');
    const closePo = e.target.closest('[data-act="po-close"]');
    if (recv) {
      const po = purchaseOrders.find(p => p.id === recv.dataset.id);
      if (!po) return;
      const alreadyReceived = po.receivedSoFar || 0;
      const remaining = po.weightOrdered > 0 ? po.weightOrdered - alreadyReceived : 1000;
      openFormModal({
        title: t('po.receive'),
        sizeLg: false,
        saveLabel: t('po.receive'),
        bodyHtml: `
          <label>${escapeHtml(t('po.weight_received'))} (g)</label>
          <input type="number" id="poRecvWeight" value="${Math.max(0, remaining)}" min="0" step="1">
          <label style="margin-top:12px;">${escapeHtml(t('po.notes'))}</label>
          <input type="text" id="poRecvNotes" placeholder="${escapeHtml(t('po.notes'))}">`,
        async onSave(modal) {
          const w = Math.max(0, num(modal.querySelector('#poRecvWeight').value, 0));
          if (w <= 0) { toast(t('exp.amount_required') || 'Enter a weight', 'error'); return false; }
          const notes = modal.querySelector('#poRecvNotes').value.trim();
          const invItem = inventory.find(i => i.id === po.itemId);
          if (invItem) {
            invItem.weight = Math.min((invItem.weight || 0) + w, 99000);
            if (!invItem.usageHistory) invItem.usageHistory = [];
            invItem.usageHistory.unshift({ type: 'received', orderId: po.id, weightUsed: -w, date: new Date().toISOString().split('T')[0], notes });
            if (invItem.usageHistory.length > 200) invItem.usageHistory.length = 200;
            renderInventory();
          }
          po.receivedSoFar = alreadyReceived + w;
          if (po.weightOrdered > 0 && po.receivedSoFar >= po.weightOrdered) {
            po.status = 'received';
            po.receivedAt = new Date().toISOString().split('T')[0];
            toast(t('po.received_toast') + ' · +' + w + 'g', 'success');
          } else {
            po.status = 'partial';
            toast(t('po.partial') + ' · +' + w + 'g', 'success');
          }
          // Automatically create an expense record for the received goods
          if (po.totalCost > 0 || po.unitCost > 0) {
            const expAmount = po.totalCost > 0 ? +((w / Math.max(1, po.weightOrdered)) * po.totalCost).toFixed(2) : +(w * (po.unitCost || 0) / 1000).toFixed(2);
            if (expAmount > 0) {
              expenses.push({
                id:       uid('EXP'),
                date:     new Date().toISOString().split('T')[0],
                amount:   expAmount,
                category: 'filament',
                note:     `${t('po.receive') || 'PO receive'}: ${po.id}${notes ? ' — ' + notes : ''}`,
                orderId:  null,
                poId:     po.id,
              });
              renderExpenses?.();
            }
          }
          saveAll();
          renderPurchaseOrders();
          return true;
        }
      });
    }
    if (closePo) {
      const po = purchaseOrders.find(p => p.id === closePo.dataset.id);
      if (po) {
        po.status = 'received';
        po.receivedAt = new Date().toISOString().split('T')[0];
        saveAll();
        renderPurchaseOrders();
        toast(t('po.received_toast'), 'success');
      }
    }
    if (del) {
      const ok = await confirmModal(t('common.delete') + '?', { danger: true });
      if (!ok) return;
      purchaseOrders = purchaseOrders.filter(p => p.id !== del.dataset.id);
      saveAll();
      renderPurchaseOrders();
    }
    const recInv = e.target.closest('[data-act="po-record-invoice"]');
    if (recInv) recordSupplierInvoice(recInv.dataset.id);
  });

  // Batch generate POs for low-stock items (Feature 5 new 8-pack)
  document.addEventListener('click', (e) => {
    const batchBtn = e.target.closest('[data-act="batch-gen-pos"]');
    if (batchBtn) batchGenPOs();
  });

  // Row-actions dropdown: toggle open on ⋯ click, close on outside click
  document.addEventListener('click', (e) => {
    const moreBtn = e.target.closest('.row-more-btn');
    if (moreBtn) {
      e.stopPropagation();
      const id   = moreBtn.dataset.id;
      const menu = document.querySelector(`.row-actions-menu[data-for="${CSS.escape(id)}"]`);
      if (!menu) return;
      const isOpen = menu.classList.contains('open');
      // Close all open menus first
      document.querySelectorAll('.row-actions-menu.open').forEach(m => {
        m.classList.remove('open');
        m.previousElementSibling?.setAttribute('aria-expanded', 'false');
      });
      if (!isOpen) {
        menu.classList.add('open');
        moreBtn.setAttribute('aria-expanded', 'true');
      }
      return;
    }
    // Click outside any menu → close all
    if (!e.target.closest('.row-actions-menu')) {
      document.querySelectorAll('.row-actions-menu.open').forEach(m => {
        m.classList.remove('open');
        m.previousElementSibling?.setAttribute('aria-expanded', 'false');
      });
    }
  });

  // Keyboard: close dropdown on Escape
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      document.querySelectorAll('.row-actions-menu.open').forEach(m => {
        m.classList.remove('open');
        m.previousElementSibling?.setAttribute('aria-expanded', 'false');
      });
    }
  }, { capture: false });
}

  const api = { initialRender, wireEvents };
  Object.assign(global, api);
  global.KhaytWireEvents = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : window);
